### PR TITLE
WIP: 2.7.0 Redone

### PR DESCRIPTION
**Pull request by hmaarrfk**
Trying to refactor a few PRs made to the tensorflow 2.7.0 attempt
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by h-vetinari** [comment]
So this seems to be missing at least the commits that actually bump to 2.7.0 😅 

Also what's the idea behind the commit here? Putting all the dependencies into the global requirements, rather than per-output? While that should have the same result, I think it's a bit misleading, so I'm not the biggest fan.

**Comment by xhochy** [comment]
With outputs, we shouldn't have a name that matches an output. This triggers a lot of odd behaviours in conda-build, I had quite a pain with that in the past.

**Comment by hmaarrfk** [comment]
i guess i was trying to take advantage of the oddities.

I really don't like the duplication of the dependencies.

but the goal here is to cleanup the dependencies, before moving to 2.7. i appreciate the feedback.

for example, in 2.6.2 i unpinned a dependency on `split` but not on base, so it didn't really do anything.

**Comment by xhochy** [comment]
I don't think we even need the top-level dependencies, we can possibly drop them.

**Comment by hmaarrfk** [comment]
the `build.sh` script does some heavy lifting. do you want to push to this branch to demo the reorg you are suggesting?

**Comment by xhochy** [comment]
> the `build.sh` script does some heavy lifting. do you want to push to this branch to demo the reorg you are suggesting?

Ah, damn. I forgot that we also have `libtensorflow*` outputs 🤦

**Comment by hmaarrfk** [comment]
I think i got the pip command wrong. Would you prefer strange `conda-build` behavior, or fancy jinja syntax?

**Comment by hmaarrfk** [comment]
Fancy jinja syntax used:
https://github.com/conda-forge/tensorflow-feedstock/pull/196

**Pull request closed without merging**
