### PR TITLE
WIP: Numpy matrix

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
Why?

**Comment by h-vetinari** [comment]
The PR is low on context, but contains a crucial link with the added test: https://github.com/tensorflow/tensorflow/issues/47691#issuecomment-889506604. Tensorflow is not compatible with 1.20/1.21 ATM - I guess @hmaarrfk wanted to test the result/fallout in the context of eventually unpinning numpy (see #151)...?

**Comment by hmaarrfk** [comment]
sorry. i was reading up on what was incompatible between numpy and tensorflow and i think what remain today is a few misunderstandings of the python API.

I'm attempting to see if we can unpin bumpy to move compatibility forward. It seems that upstream might soon do it, so I'm weary of unpinning things ourselves. 

This is mostly an experiment at this stage. 

Tank you @h-vetinari for explaining

**Comment by hmaarrfk** [comment]
I'm quite hopeful for good results here

**Comment by njzjz** [comment]
I think tensorflow/tensorflow#47691 has been fixed by tensorflow/tensorflow#47951, though. I am not sure why it is still open.

**Comment by njzjz** [comment]
I think tensorflow/tensorflow#47691 has been fixed by tensorflow/tensorflow#47957, though. I am not sure why it is still open.

**Comment by h-vetinari** [comment]
At least https://github.com/tensorflow/tensorflow/pull/48935 is still open.

**Comment by hmaarrfk** [comment]
yeah, it seems that they have 1 issue remaining that they want a test for before merging in.

**Comment by hmaarrfk** [comment]
Seems like this is addressed in 2.7.0

**Pull request closed without merging**
