### PR TITLE
Icu73 turbo3

### PR DESCRIPTION
**Pull request by hmaarrfk**
lets see if we get lucky, then we can save on some storage space.....
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge/tensorflow is anybody able to build OSX? I am done linux + cuda but forgot I couldn't build OSX easily...

**Comment by hmaarrfk** [comment]
linux logs [log_files.zip](https://github.com/conda-forge/tensorflow-feedstock/files/12787262/log_files.zip)

**Comment by xhochy** [comment]
Later this week, I would have some time for this.

**Comment by xhochy** [comment]
You can find the OSX build on my [`uwe.korn-tf-gpu` channel](https://anaconda.org/uwe.korn-tf-gpu/dashboard) with the following logs:

* [osx_64_numpy1.23python3.11.____cpython.log](https://gist.github.com/xhochy/b39c223001960197b24e7a3d821f1696#file-osx_64_numpy1-23python3-11-____cpython-log)
* [osx_64_numpy1.22python3.8.____cpython.log](https://gist.github.com/xhochy/3366beb9954af1c2808ecfe1eb2963df#file-osx_64_numpy1-22python3-8-____cpython-log)
* [osx_64_numpy1.22python3.9.____cpython.log](https://gist.github.com/xhochy/2371b824c84f4ccbd228eb5eeed937c3#file-osx_64_numpy1-22python3-9-____cpython-log)
* [osx_64_numpy1.22python3.10.____cpython.log](https://gist.github.com/xhochy/eba0bbfb6f4e549d95349e241ed1f298#file-osx_64_numpy1-22python3-10-____cpython-log)
* [osx_arm64_numpy1.23python3.11.____cpython.log](https://gist.github.com/xhochy/e4a41d6287a2563e03d3f50ba312ebc1#file-osx_arm64_numpy1-23python3-11-____cpython-log)
* [osx_arm64_numpy1.22python3.9.____cpython.log](https://gist.github.com/xhochy/4266acd26e74271155f07db755807518#file-osx_arm64_numpy1-22python3-9-____cpython-log)
* [osx_arm64_numpy1.22python3.8.____cpython.log](https://gist.github.com/xhochy/4ecd9ad6900771d9f191e475eaabc035#file-osx_arm64_numpy1-22python3-8-____cpython-log)
* [osx_arm64_numpy1.22python3.10.____cpython.log](https://gist.github.com/xhochy/ee6eaa1bc26a2f740bd465245ab2b5bd#file-osx_arm64_numpy1-22python3-10-____cpython-log)

**Comment by hmaarrfk** [comment]
Thank you

**Comment by hmaarrfk** [comment]
Using Anaconda API: https://api.anaconda.org
Copied file: osx-64/tensorflow-base-2.12.1-cpu_py310h72f9296_1.conda
Copied file: osx-64/tensorflow-base-2.12.1-cpu_py311h0cd1a8d_1.conda
Copied file: osx-64/tensorflow-base-2.12.1-cpu_py38h7595b79_1.conda
Copied file: osx-64/tensorflow-base-2.12.1-cpu_py39hbf49819_1.conda
Copied file: osx-arm64/tensorflow-base-2.12.1-cpu_py310h6202087_1.conda
Copied file: osx-arm64/tensorflow-base-2.12.1-cpu_py311hda9fa7b_1.conda
Copied file: osx-arm64/tensorflow-base-2.12.1-cpu_py38h7de3861_1.conda
Copied file: osx-arm64/tensorflow-base-2.12.1-cpu_py39hd1a7ea3_1.conda
Copied 8 files!
Using Anaconda API: https://api.anaconda.org
Copied file: osx-64/tensorflow-2.12.1-cpu_py310h22f808f_1.conda
Copied file: osx-64/tensorflow-2.12.1-cpu_py311hfac9faf_1.conda
Copied file: osx-64/tensorflow-2.12.1-cpu_py38he866dac_1.conda
Copied file: osx-64/tensorflow-2.12.1-cpu_py39hb0a6171_1.conda
Copied file: osx-arm64/tensorflow-2.12.1-cpu_py310h6ecea76_1.conda
Copied file: osx-arm64/tensorflow-2.12.1-cpu_py311hfb078d8_1.conda
Copied file: osx-arm64/tensorflow-2.12.1-cpu_py38h4487131_1.conda
Copied file: osx-arm64/tensorflow-2.12.1-cpu_py39h2839aeb_1.conda
Copied 8 files!
Using Anaconda API: https://api.anaconda.org
Copied file: osx-64/tensorflow-estimator-2.12.1-cpu_py310hab81a81_1.conda
Copied file: osx-64/tensorflow-estimator-2.12.1-cpu_py311he0cccdc_1.conda
Copied file: osx-64/tensorflow-estimator-2.12.1-cpu_py38hf190324_1.conda
Copied file: osx-64/tensorflow-estimator-2.12.1-cpu_py39h8a426f1_1.conda
Copied file: osx-arm64/tensorflow-estimator-2.12.1-cpu_py310h8b6e46b_1.conda
Copied file: osx-arm64/tensorflow-estimator-2.12.1-cpu_py311h2516bc8_1.conda
Copied file: osx-arm64/tensorflow-estimator-2.12.1-cpu_py38hceb852f_1.conda
Copied file: osx-arm64/tensorflow-estimator-2.12.1-cpu_py39h9989bb1_1.conda
Copied 8 files!
Using Anaconda API: https://api.anaconda.org
Copied file: osx-64/libtensorflow-2.12.1-cpu_h76a68ed_1.conda
Copied file: osx-arm64/libtensorflow-2.12.1-cpu_h8bdb520_1.conda
Copied 2 files!
Using Anaconda API: https://api.anaconda.org
Copied file: osx-64/libtensorflow_cc-2.12.1-cpu_h9ec4201_1.conda
Copied file: osx-arm64/libtensorflow_cc-2.12.1-cpu_hd34dfa9_1.conda
Copied 2 files!
Using Anaconda API: https://api.anaconda.org
Copied file: osx-64/tensorflow-cpu-2.12.1-cpu_py310he781eb1_1.conda
Copied file: osx-64/tensorflow-cpu-2.12.1-cpu_py311he781eb1_1.conda
Copied file: osx-64/tensorflow-cpu-2.12.1-cpu_py38he781eb1_1.conda
Copied file: osx-64/tensorflow-cpu-2.12.1-cpu_py39he781eb1_1.conda
Copied file: osx-arm64/tensorflow-cpu-2.12.1-cpu_py310hd610c6a_1.conda
Copied file: osx-arm64/tensorflow-cpu-2.12.1-cpu_py311hd610c6a_1.conda
Copied file: osx-arm64/tensorflow-cpu-2.12.1-cpu_py38hd610c6a_1.conda
Copied file: osx-arm64/tensorflow-cpu-2.12.1-cpu_py39hd610c6a_1.conda
Copied 8 files!

**Comment by hmaarrfk** [comment]
we really should find a way to share the libraries accross them. Uploading 400MB 4 times is not a super good use of space....

**Pull request merged**
