### PR TITLE
Update to 0.9.0rc0

### PR DESCRIPTION
**Pull request by danielfrg**
Update to `0.9.0rc0` now they released linux and python 3.4 wheel so its now supported :)

I added mysellf as maintainer hopefully thats ok.

### CODE REVIEW

**Comment by jakirkham** [comment]
See this discussion about rc and dev releases. ( https://github.com/conda-forge/conda-forge.github.io/issues/147 ) Unfortunately, this is not settled.

**Comment by danielfrg** [comment]
Thanks for the link to the discussion @jakirkham. I'll let this open for now and update to `0.9.0` when its released finally.

**Comment by jakirkham** [comment]
FWIW, I think everyone wants to see this. So, it isn't a question of whether, but how this happens. Also, there is a related question of how one can control which packages use dev/rc releases.

**Comment by jjhelmus** [comment]
@danielfrg This looks good, but I agree that we should wait until `0.9.0` is relased to create a conda package.  

Related I see in the **Major Features and Improvements** section of the release a point on "Added makefile for better cross-platform build support (C API only)".  Have you examined this at all?  Will it allow us to build the package from source without needing to install Bazel?

**Comment by jjhelmus** [comment]
Sorry to answer my own question, but it looks like the make is only for creating a static C++ tensorflow library not for the Python package, [details here](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile).

**Comment by jjhelmus** [comment]
Closing now that #9 has been merged which updates to 0.9.0.

**Pull request closed without merging**
