### PR TITLE
Dont clobber tensorboard

### PR DESCRIPTION
**Pull request by jschueller**
tensorboard and tensorflow conflict on windows, see the gplow feedstock:

2019-06-18T06:10:04.8359933Z ERROR:conda.stderr:
2019-06-18T06:10:04.8360465Z ClobberWarning: Conda was asked to clobber an existing path.
2019-06-18T06:10:04.8360756Z source path: C:\Miniconda\pkgs\tensorflow-1.10.0-py36_0\Scripts\tensorboard.exe
2019-06-18T06:10:04.8361064Z target path: D:\bld\gpflow_1560837524273_test_env\Scripts\tensorboard.exe
2019-06-18T06:10:04.8361282Z

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jschueller** [comment]
oh, it does not build on windows anymore ?

**Comment by jschueller** [comment]
@conda-forge-admin, please rerender

**Comment by jschueller** [comment]
I dont understand why tensorboard.exe does not work from the test section anymore, doesn't it come from the tensorboard recipe ?

**Comment by bgruening** [comment]
@jschueller can you rebase against the latest master and try again?

**Comment by hajapy** [comment]
Isn’t this no longer needed? The tensorboard bin is removed now.

**Comment by hajapy** [comment]
Closing as I believe this is no longer relevant.

**Pull request closed without merging**
