### PR TITLE
2.4.4 version

### PR DESCRIPTION
**Pull request by tylerpotts**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by tylerpotts** [comment]
@conda-forge-admin, please rerender

**Comment by tylerpotts** [comment]
I'm adding this because I need version 2.4.4 to be available in conda forge to resolve some CVEs. I would use the latest version, but I also need to have Tensorflow play nice with OpenCV, and this should allow me to do that.

I'm not really sure the steps for adding an older version of the package, as it seems I would need to undo some of the work in more recent commits. This current PR is based off the commit for the `v2.4.3` release. Any guidance in this direction would be appreciated.

CC @ghoersti

**Comment by hmaarrfk** [comment]
Why doesn't tensorflow play nice with opencv on conda-forge? can you provide your environment and an example of the conflict.

**Comment by tylerpotts** [comment]
@hmaarrfk Thanks for the reply!

This minimal example isn't resolving:
```
name: basictensor
channels:
  - conda-forge
dependencies:
  - tensorflow=2.6.2
  - opencv
```

Solving with `mamba env create -f <file>` errors with the following:

```
$ mamba env create -f basic.yaml -d
pkgs/main/linux-64       [====================] (00m:00s) No change
pkgs/main/noarch         [====================] (00m:00s) No change
pkgs/r/linux-64          [====================] (00m:00s) No change
pkgs/r/noarch            [====================] (00m:00s) No change
conda-forge/noarch       [====================] (00m:02s) Done
conda-forge/linux-64     [====================] (00m:05s) Done


Looking for: ['tensorflow=2.6.2', 'opencv']


Encountered problems while solving:
  - nothing provides libopencv 4.2.0 py36_5 needed by opencv-4.2.0-py36_5
```

Solving with `conda env create -f <file>` fails as well, but the error message is less useful:
```
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
tensorflow=2.6.2 -> python[version='>=3.7,<3.8.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0']
tensorflow=2.6.2 -> python_abi=3.9[build=*_cp39] -> python[version='3.7.*|3.9.*|3.8.*']

Package libgcc-ng conflicts for:
tensorflow=2.6.2 -> python[version='>=3.9,<3.10.0a0'] -> libgcc-ng[version='>=4.9|>=7.3.0|>=9.3.0|>=7.2.0']
tensorflow=2.6.2 -> libgcc-ng[version='>=7.5.0|>=9.4.0']

Package libprotobuf conflicts for:
opencv -> libopencv==4.5.3=py39h7d09d5f_7 -> libprotobuf[version='>=3.15.6,<3.16.0a0|>=3.15.8,<3.16.0a0|>=3.16.0,<3.17.0a0|>=3.18.1,<3.19.0a0|>=3.19.1,<3.20.0a0']
tensorflow=2.6.2 -> tensorflow-base==2.6.2=cpu_py39h6349a3b_2 -> libprotobuf[version='>=3.18.1,<3.19.0a0']
opencv -> libprotobuf[version='>=3.4.1,<3.5.0a0|>=3.5.2,<3.6.0a0']

Package openssl conflicts for:
tensorflow=2.6.2 -> openssl[version='>=1.1.1l,<1.1.2a']
tensorflow=2.6.2 -> python[version='>=3.9,<3.10.0a0'] -> openssl[version='>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1h,<1.1.2a|>=1.1.1i,<1.1.2a|>=1.1.1j,<1.1.2a|>=1.1.1k,<1.1.2a|>=3.0.0,<4.0a0|>=1.1.1d,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1f,<1.1.2a']

Package libstdcxx-ng conflicts for:
tensorflow=2.6.2 -> libstdcxx-ng[version='>=7.5.0|>=9.4.0']
tensorflow=2.6.2 -> python[version='>=3.9,<3.10.0a0'] -> libstdcxx-ng[version='>=4.9|>=7.3.0|>=9.3.0|>=7.2.0']

Package python_abi conflicts for:
tensorflow=2.6.2 -> python_abi[version='3.7.*|3.9.*|3.8.*',build='*_cp37m|*_cp39|*_cp38']
tensorflow=2.6.2 -> python[version='>=3.7,<3.8.0a0'] -> python_abi==3.7[build=*_pypy37_pp73]The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__cuda==11.2=0
  - feature:/linux-64::__glibc==2.31=0
  - feature:|@/linux-64::__cuda==11.2=0
  - feature:|@/linux-64::__glibc==2.31=0
  - opencv -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
```

**Comment by izahn** [comment]
This is because tensorflow needs icu 69 but https://github.com/conda-forge/qt-feedstock/pull/207 hasn't been merged yet. I encourage everyone to try to "fail forward" by updating the qt build rather than trying to maintain older versions of tensorflow.

**Comment by tylerpotts** [comment]
@izahn Thanks for the guidance. I'll close this out and track the qt PR

**Comment by hmaarrfk** [comment]
I think requiring 2.6.2 is going to be quite hard.

Why not ask to install:

```
mamba create --name tf_cv "opencv>=4.5" "tensorflow>=2.6"
```
this seems to converge.

**Comment by izahn** [comment]
> I think requiring 2.6.2 is going to be quite hard.
> 
> Why not ask to install:
> 
> ```
> mamba create --name tf_cv "opencv>=4.5" "tensorflow>=2.6"
> ```
> 
> this seems to converge.

2.6.0 doesn't include fixes for the CVE's that prompted this PR to begin with

**Pull request closed without merging**
