### PR TITLE
Update to 2.2.0

### PR DESCRIPTION
**Pull request by jschueller**
@conda-forge-admin please rerender

### CODE REVIEW

**Comment by jschueller** [comment]
seems like the linux build is taking 6hours+ :(

**Comment by EelcoHoogendoorn** [comment]
Just wanted to say I am glad to see someone is trying. Has there ever been any talk of getting the tf developers involved in supporting these recipes? I imagine this process would be easier if the tf developers would be in tune with the realities of building binaries for all platforms as early in the development cycle as possible.

**Comment by marcelotrevisani** [comment]
I am trying to build it locally, lets see

**Comment by marcelotrevisani** [comment]
``libtensorflow`` returned the following error
```
+ /home/bb8/miniconda3/conda-bld/tensorflow_1594045278166/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/x86_64-conda_cos6-linux-gnu-cc -o test_c -L/home/bb8/miniconda3/conda-bld/tensorflow_1594045278166/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/ -ltensorflow -I/home/bb8/miniconda3/conda-bld/tensorflow_1594045278166/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/include/ test_c.c
In file included from test_c.c:2:0:
/home/bb8/miniconda3/conda-bld/tensorflow_1594045278166/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/include/tensorflow/c/c_api.h:22:38: fatal error: tensorflow/c/tf_attrtype.h: No such file or directory
compilation terminated.
+ exit 0
```

I think we need to update the tests for libtensorflow


For ``libtensorflow_cc`` was the same thing

```
+ test -f /home/bb8/miniconda3/conda-bld/tensorflow_1594045278166/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/libtensorflow_cc.so
+ /home/bb8/miniconda3/conda-bld/tensorflow_1594045278166/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/x86_64-conda_cos6-linux-gnu-c++ -std=c++11 -o test_cc -L/home/bb8/miniconda3/conda-bld/tensorflow_1594045278166/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/ -ltensorflow_cc -ltensorflow_framework -lrt -I/home/bb8/miniconda3/conda-bld/tensorflow_1594045278166/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/include/ test_cc.cc
In file included from test_cc.cc:3:0:
/home/bb8/miniconda3/conda-bld/tensorflow_1594045278166/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/include/tensorflow/core/public/session.h:22:60: fatal error: tensorflow/core/framework/device_attributes.pb.h: No such file or directory
compilation terminated.
+ exit 0
```


And it failed to import ``tensorflow``
```
Traceback (most recent call last):
  File "/home/bb8/miniconda3/conda-bld/tensorflow_1594045278166/test_tmp/run_test.py", line 2, in <module>
    import tensorflow
ModuleNotFoundError: No module named 'tensorflow'
import: 'tensorflow'

```

**Comment by marcelotrevisani** [comment]
@conda-forge-admin , please rerender

**Comment by CJ-Wright** [comment]
@conda-forge-admin please rerender

**Comment by jakirkham** [comment]
If someone is able to build this locally and upload it to their own Anaconda.org channel, we can copy it over to `conda-forge` per [CFEP-03]( https://github.com/conda-forge/cfep/blob/master/cfep-03.md ).

**Comment by marcelotrevisani** [comment]
> If someone is able to build this locally and upload it to their own Anaconda.org channel, we can copy it over to `conda-forge` per [CFEP-03](https://github.com/conda-forge/cfep/blob/master/cfep-03.md).

I built that locally but the tests were failing. I can give another try, but it needs a bit of debugging 
on my machine I just checked and it takes 45min to run the entire conda build for tensorflow

**Comment by njzjz** [comment]
Please modify
https://github.com/conda-forge/tensorflow-feedstock/blob/9118fe1d94197a81ae0f871f4a6040b34a02aaa3/recipe/cp_libtensorflow_cc.sh#L3-L4
to
```
cp bazel-bin/tensorflow/libtensorflow_cc.so* ${PREFIX}/lib/ 
cp bazel-bin/tensorflow/libtensorflow_framework.so* ${PREFIX}/lib/ 
cp -d $PREFIX/lib/libtensorflow_framework.so.2 $PREFIX/lib/libtensorflow_framework.so
```
since Tensorflow changed the name of the library.

**Comment by marcelotrevisani** [comment]
> Please modify
> 
> https://github.com/conda-forge/tensorflow-feedstock/blob/9118fe1d94197a81ae0f871f4a6040b34a02aaa3/recipe/cp_libtensorflow_cc.sh#L3-L4
> 
> to
> 
> ```shell
> cp bazel-bin/tensorflow/libtensorflow_cc.so* ${PREFIX}/lib/ 
> cp bazel-bin/tensorflow/libtensorflow_framework.so* ${PREFIX}/lib/ 
> cp -d $PREFIX/lib/libtensorflow_framework.so.2 $PREFIX/lib/libtensorflow_framework.so
> ```
> 
> since Tensorflow changed the name of the library.

I changed it but it is still failing

**Comment by marcelotrevisani** [comment]
> Please modify
> 
> https://github.com/conda-forge/tensorflow-feedstock/blob/9118fe1d94197a81ae0f871f4a6040b34a02aaa3/recipe/cp_libtensorflow_cc.sh#L3-L4
> 
> to
> 
> ```shell
> cp bazel-bin/tensorflow/libtensorflow_cc.so* ${PREFIX}/lib/ 
> cp bazel-bin/tensorflow/libtensorflow_framework.so* ${PREFIX}/lib/ 
> cp -d $PREFIX/lib/libtensorflow_framework.so.2 $PREFIX/lib/libtensorflow_framework.so
> ```
> 
> since Tensorflow changed the name of the library.

It is failing because it is missing those ``.pb.h`` files

**Comment by jschueller** [comment]
any ideas for osx/win ?

**Comment by 183amir** [comment]
can we skip win and osx builds for now to get some traction?

**Comment by 183amir** [comment]
Hi guys,

I am trying to set up a CI for tensorflow in our Gitlab instance so that we can build tensorflow packages there and you upload them to conda-forge manually. I am pushing this branch to https://gitlab.idiap.ch/bob/conda/-/tree/conda-forge-tensorflow-feedstock We have a Linux and a Mac runner but for now I just set up the Linux builds. Unfortunately, the Python 3.6 builds are failing:
https://gitlab.idiap.ch/bob/conda/pipelines/45547 (the other two are still running as of writing).
It is failing with:
```
 INFO: From ProtoCompile tensorflow/lite/toco/model_flags.pb.h:
bazel-out/k8-opt/bin/external/com_google_protobuf/src: warning: directory does not exist.
INFO: From ProtoCompile tensorflow/python/framework/cpp_shape_inference.pb.h:
bazel-out/k8-opt/bin/external/com_google_protobuf/src: warning: directory does not exist.
[6,974 / 8,653] Compiling tensorflow/python/client/tf_session_wrapper.cc; 273s local ... (40 actions, 39 running)
ERROR: /home/conda/feedstock_root/build_artifacts/tensorflow_1605267226501/work/tensorflow/python/BUILD:437:1: C++ compilation of rule '//tensorflow/python:bfloat16_lib' failed (Exit 1)
tensorflow/python/lib/core/bfloat16.cc: In function 'bool tensorflow::{anonymous}::Initialize()':
tensorflow/python/lib/core/bfloat16.cc:636:36: error: no match for call to '(tensorflow::{anonymous}::Initialize()::<lambda(const char*, PyUFuncGenericFunction, const std::array<int, 3>&)>) (const char [6], <unresolved overloaded function type>, const std::array<int, 3>&)'
                       compare_types)) {
                                    ^
tensorflow/python/lib/core/bfloat16.cc:610:60: note: candidate: tensorflow::{anonymous}::Initialize()::<lambda(const char*, PyUFuncGenericFunction, const std::array<int, 3>&)>
                             const std::array<int, 3>& types) {
                                                            ^
tensorflow/python/lib/core/bfloat16.cc:610:60: note:   no known conversion for argument 2 from '<unresolved overloaded function type>' to 'PyUFuncGenericFunction {aka void (*)(char**, const long int*, const long int*, void*)}'
tensorflow/python/lib/core/bfloat16.cc:640:36: error: no match for call to '(tensorflow::{anonymous}::Initialize()::<lambda(const char*, PyUFuncGenericFunction, const std::array<int, 3>&)>) (const char [10], <unresolved overloaded function type>, const std::array<int, 3>&)'
                       compare_types)) {
                                    ^
tensorflow/python/lib/core/bfloat16.cc:610:60: note: candidate: tensorflow::{anonymous}::Initialize()::<lambda(const char*, PyUFuncGenericFunction, const std::array<int, 3>&)>
                             const std::array<int, 3>& types) {
                                                            ^
tensorflow/python/lib/core/bfloat16.cc:610:60: note:   no known conversion for argument 2 from '<unresolved overloaded function type>' to 'PyUFuncGenericFunction {aka void (*)(char**, const long int*, const long int*, void*)}'
tensorflow/python/lib/core/bfloat16.cc:643:77: error: no match for call to '(tensorflow::{anonymous}::Initialize()::<lambda(const char*, PyUFuncGenericFunction, const std::array<int, 3>&)>) (const char [5], <unresolved overloaded function type>, const std::array<int, 3>&)'
   if (!register_ufunc("less", CompareUFunc<Bfloat16LtFunctor>, compare_types)) {
                                                                             ^
tensorflow/python/lib/core/bfloat16.cc:610:60: note: candidate: tensorflow::{anonymous}::Initialize()::<lambda(const char*, PyUFuncGenericFunction, const std::array<int, 3>&)>
                             const std::array<int, 3>& types) {
                                                            ^
tensorflow/python/lib/core/bfloat16.cc:610:60: note:   no known conversion for argument 2 from '<unresolved overloaded function type>' to 'PyUFuncGenericFunction {aka void (*)(char**, const long int*, const long int*, void*)}'
tensorflow/python/lib/core/bfloat16.cc:647:36: error: no match for call to '(tensorflow::{anonymous}::Initialize()::<lambda(const char*, PyUFuncGenericFunction, const std::array<int, 3>&)>) (const char [8], <unresolved overloaded function type>, const std::array<int, 3>&)'
                       compare_types)) {
                                    ^
tensorflow/python/lib/core/bfloat16.cc:610:60: note: candidate: tensorflow::{anonymous}::Initialize()::<lambda(const char*, PyUFuncGenericFunction, const std::array<int, 3>&)>
                             const std::array<int, 3>& types) {
                                                            ^
tensorflow/python/lib/core/bfloat16.cc:610:60: note:   no known conversion for argument 2 from '<unresolved overloaded function type>' to 'PyUFuncGenericFunction {aka void (*)(char**, const long int*, const long int*, void*)}'
tensorflow/python/lib/core/bfloat16.cc:651:36: error: no match for call to '(tensorflow::{anonymous}::Initialize()::<lambda(const char*, PyUFuncGenericFunction, const std::array<int, 3>&)>) (const char [11], <unresolved overloaded function type>, const std::array<int, 3>&)'
                       compare_types)) {
                                    ^
tensorflow/python/lib/core/bfloat16.cc:610:60: note: candidate: tensorflow::{anonymous}::Initialize()::<lambda(const char*, PyUFuncGenericFunction, const std::array<int, 3>&)>
                             const std::array<int, 3>& types) {
                                                            ^
tensorflow/python/lib/core/bfloat16.cc:610:60: note:   no known conversion for argument 2 from '<unresolved overloaded function type>' to 'PyUFuncGenericFunction {aka void (*)(char**, const long int*, const long int*, void*)}'
tensorflow/python/lib/core/bfloat16.cc:655:36: error: no match for call to '(tensorflow::{anonymous}::Initialize()::<lambda(const char*, PyUFuncGenericFunction, const std::array<int, 3>&)>) (const char [14], <unresolved overloaded function type>, const std::array<int, 3>&)'
                       compare_types)) {
                                    ^
tensorflow/python/lib/core/bfloat16.cc:610:60: note: candidate: tensorflow::{anonymous}::Initialize()::<lambda(const char*, PyUFuncGenericFunction, const std::array<int, 3>&)>
                             const std::array<int, 3>& types) {
                                                            ^
tensorflow/python/lib/core/bfloat16.cc:610:60: note:   no known conversion for argument 2 from '<unresolved overloaded function type>' to 'PyUFuncGenericFunction {aka void (*)(char**, const long int*, const long int*, void*)}'
INFO: Elapsed time: 6839.362s, Critical Path: 2207.64s
```

If you provide correct recipes for tensorflow to be built on Linux and Mac, I can pull these recipes into our Gitlab and build them there. Then, we can upload them to conda-forge. I can only commit our CI times for *working* recipes and I don't have the experience of compiling Tensorflow from source.

Please let me know if this way of building tensorflow is something desirable for conda-forge. I can also set up a similar branch for Pytorch. It's a shame these 2 packages are not in conda-forge.

**Comment by 183amir** [comment]
Looks like the issue is similar to https://github.com/tensorflow/tensorflow/issues/41061

**Comment by 183amir** [comment]
@conda-forge-admin please rerender

**Comment by FernandezMathieu** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
Opened an attempt to continue this forward in #110 - any help welcome.

**Pull request closed without merging**
