### PR TITLE
v12.1 released.

### PR DESCRIPTION
**Pull request by QtRoS**
I am not sure if only these changes are required for transition to 12.1

### CODE REVIEW

**Comment by babhishek21** [comment]
Looks alright! I was wondering though: Shouldn't we also have CI builds for Windows and Linux (say Ubuntu)?

**Comment by QtRoS** [comment]
Hm, I can see this in README page:

> Current build status
> Linux: Circle CI OSX: TravisCI Windows: 

Does it mean that you already have linux build? 
BTW my idea was just to upgrade version. Is my commit enough for that purpose?

**Comment by babhishek21** [comment]
> Current build status
> Linux: Circle CI

That's strange. This pull request did not run on CircleCI. I can only see the OSX build checks from TravisCI. Maybe the repository owners removed those integrations.

>BTW my idea was just to upgrade version. Is my commit enough for that purpose?

It should be. Sometimes the dependencies change. In that case, the recipe needs further modification. But if the CI build passes, then I guess everything is alright.

**Comment by QtRoS** [comment]
So, can someone approve it?

**Comment by jjhelmus** [comment]
tensorflow `0.12.1` has updated requirements which need to be included in the recipe.  Specifically:

* wheel
* six (>=1.10.0)
* protobuf (>=3.1.0)
* numpy (>=1.11.0)
* mock (>=2.0.0)

The selectors should be updated to add support for Windows. 

Finally this feedstock should be rerendered to pick up the latest updates in conda-smithy.

See #23 for details on how these steps can be accomplished.  I believe the lack of a protobuf 3.1.0 package may be a blocker here.

**Comment by QtRoS** [comment]
@jjhelmus is it ok now? What should we do next? Add 3.1.0 version of protobuf?
As I already mentioned my idea was just to upgrade version (nothing more about windows support). Of course we can do both things simultaneously, but it can take a while I think.

**Comment by babhishek21** [comment]
Travis build is failing. `protobuf == 3.1.0` isn't available yet on `conda-forge`. `protobuf == 3.0.0` is however available (see [here](https://anaconda.org/conda-forge/protobuf)).

**Comment by QtRoS** [comment]
@babhishek21 how can we bump protobuf version?

**Comment by babhishek21** [comment]
@QtRoS That would be by updating the `protobuf` feedstock ([here](https://github.com/conda-forge/protobuf-feedstock)).

An ongoing [PR](https://github.com/conda-forge/protobuf-feedstock/pull/16) is going on to update that feedstock to ver. `3.1.0`.

**Comment by jjhelmus** [comment]
Agreed that an update to `protobuf` is needed before this can be merged.  Will try to see what is causing the Windows build error there.

**Comment by QtRoS** [comment]
`protobuf` merged. Our move?

**Comment by babhishek21** [comment]
@QtRoS Refresh the CIs to rebuild. 

However [`tensorflow ver. 1.0.0-alpha`](https://github.com/tensorflow/tensorflow/releases/tag/v1.0.0-alpha) has also been released. Do note that many breaking API changes have occurred with this alpha release. I think we are better off with a stable release until *at least* a newer RC shows up.

**Comment by jjhelmus** [comment]
I think the OS X protobuf packages are still missing form Anaconda.org.  Wait a few hours and they should show up before closing/reopening this PR to restart the CIs.

**Comment by QtRoS** [comment]
@babhishek21  and why we can't upgrade version to 12.1 (it is pretty stable)?

**Comment by babhishek21** [comment]
@QtRoS It's an alpha release right now, AFAIK. This is the first phase of testing. God knows, what they might do. Until it goes RC, one can't be sure there are no fatal bugs around. *alpha* releases usually are such that they haven't even been tested on any kind of exhaustive architecture or platform spectrum. 

An RC, however has gone though several rounds of alpha and beta testing; and has no withstanding *showstopper* bugs. These usually transition to a final release without many changes.

Since stability is **not** guaranteed, you don't want thousands of `conda` users to get an *alpha* release if they don't specify the exact version during installation (which many will do). I am not sure if there is a way to specify a default release in this feedstock. In that case, maybe we can discuss about including nascent releases. Generally, people who want bleeding edge would get it from the source and build it themselves.

**Comment by QtRoS** [comment]
@babhishek21 I am pretty sure that v0.12.1 was stable... And yes, looks that I am right, check it: https://github.com/tensorflow/tensorflow/releases. I can see that "TensorFlow v0.12.1" is marked as "Latest release". So what about moving to latest **stable** release?

**Comment by jjhelmus** [comment]
protobuf 3.1.0 packages are now available for Python 2.7, 3.4 and 3.5 on Linux and OS X on Anaconda.org.  I'm going to close and re-open this PR to trigger the CIs to restart.

**Comment by babhishek21** [comment]
I don't see a Windows build in the CI checks. Why is that?

**Comment by QtRoS** [comment]
No conflicts finally!

**Comment by jjhelmus** [comment]
> I don't see a Windows build in the CI checks.

Windows support has not been added to this recipe.  It can be done in a separate PR

**Comment by jjhelmus** [comment]
Thanks @QtRoS for the update, everything look in order.  Merging.

**Pull request merged**
