### PR TITLE
build tensorflow from source

### PR DESCRIPTION
**Pull request by jjhelmus**
Let's give this a try

### CODE REVIEW

**Comment by jakirkham** [comment]
It's nice to see this @jjhelmus ! Also happy to see we have some passing Linux builds. 🎉

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by isuruf** [comment]
Linux passes with 20 minutes to spare. Should we do source builds for linux only? Also, can we use an external LLVM?

**Comment by jakirkham** [comment]
+1

**Comment by bgruening** [comment]
I'm also in favor to get the Linux builds merged and take the precompiled versions for OSX and Windows. We see a lot of downstream packages with problems due to the current state.

**Comment by ocefpaf** [comment]
Looks liek there is a consensus on merge this for Linux only.
@jjhelmus do you want to take one last pass on the recipe before we merge this?

**Comment by ocefpaf** [comment]
> I would appreciate someone taking this work and modifying it so that the builds pass on all platforms. Using the pre-compiled wheels on osx-64 and win-64 seems reasonable.

I'm leaving for the a long weekend today but I'll tackle that as soon as I get back, if no one beats me to it.

**Pull request merged**
