### PR TITLE
fix libtensorflow_cc headers

### LINKED ISSUE #83: how to use conda-forge's abseil-cpp and nsync
Is there a way to use conda-forge's `abseil-cpp` and `nsync` when compiling, but not what it download? I find the current build uses an environment
```bash
export TF_SYSTEM_LIBS="llvm,zlib_archive,com_google_protobuf,com_google_protobuf_cc,curl"
```
How to add `abseil-cpp` and `nsync` into `TF_SYSTEM_LIBS`?

The versions of conda-forge and what it download are a little different.

### PR DESCRIPTION
**Pull request by njzjz**
resolves #83 

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by njzjz** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Guessing this was addressed by PR ( https://github.com/conda-forge/tensorflow-feedstock/pull/86 ).

**Comment by njzjz** [comment]
It seems that it should be `bazel-tensorflow/external/com_google_absl/absl` instead of `bazel-bin/external/com_google_absl/absl`. The latter one have `.h` files.

**Comment by jakirkham** [comment]
Would you like to submit a correction?

**Pull request merged**
