### PR TITLE
Try building for Windows 

### PR DESCRIPTION
**Pull request by xhochy**
Let's see how far this gets.

### CODE REVIEW

**Comment by xhochy** [comment]
This hangs at 
```
(%BUILD_PREFIX%) %SRC_DIR%>./configure
You have bazel 3.1.0- (@non-git) installed.
```

This means that it is asking interactively for another configure value. If someone has a Windows machine and knows what it is asking for, this would be a chance to contribute to this PR ;)

**Comment by h-vetinari** [comment]
I'm happy to contribute again (even directly if you want to give me push access to your fork).

Re: Bazel, the first cf-[builds](https://anaconda.org/conda-forge/bazel/files) for windows are for 3.6.0, might it not be easier to patch out the hard version requirement and try with a newer bazel version?

**Comment by xhochy** [comment]
> I'm happy to contribute again (even directly if you want to give me push access to your fork).

Done, happy pushing :)

**Comment by wagnerpeer** [comment]
Is there any progress? I am willing to help!

**Comment by xhochy** [comment]
> Is there any progress? I am willing to help!

Can you try to run this locally and see what type of input it requires? CI is currently stuck as the script interactively asks for a value and that is not visible at all.

**Comment by h-vetinari** [comment]
I honestly have no idea how this picks up the CUDA migration (e.g. #179) that hasn't been merged yet. 🤷

**Comment by h-vetinari** [comment]
@wolfv @jaimergp @jakirkham 
Any idea what might be causing the following resolver error?
```
Mamba failed to solve:
 - vs2019_win-64
 - cuda_win-64 11.2.*
```

**Comment by h-vetinari** [comment]
Woop woop, managed to find a way through the hangs-in-`configure.py`-maze! 🥳 

This is now ready & fair game for further iteration @hmaarrfk et al.

**Comment by wolfv** [comment]
Nice! 🎉

**Comment by jaimergp** [comment]
`cuda_win-64 11.2.*` does not exist. You need `nvcc_win-64`, as provided by https://github.com/conda-forge/tensorflow-feedstock/pull/179

**Comment by h-vetinari** [comment]
> You need `nvcc_win-64`, as provided by #179 (e.g. copy the migrator file here and rerender)

Thanks a lot! I did that, but the rerender told me the feedstock is up-to-date already. I guess I'll have to copy the `cuda110.yaml` & `cuda111_112.yaml` too...?

**Comment by h-vetinari** [comment]
> I did that, but the rerender told me the feedstock is up-to-date already. 

Ah never mind, false alarm, sorry. I was on the wrong branch locally 🤦

**Comment by wolfv** [comment]
@h-vetinari I checked the NVIDIA website and I don't think there is NCCL for Windows.

**Comment by wolfv** [comment]
Hmm, I stand corrected: https://github.com/MyCaffe/NCCL looks like it's possible to build NCCL for windows.

**Comment by bjarthur** [comment]
would be great to have tensorflow-gpu working on windows!

**Comment by sh-shahrokhi** [comment]
Hello, is there any chance that we can the Windows build to work? Even the recent CPU only builds would be great. I am also willing to help.

**Comment by eabase** [comment]
bump

**Comment by eabase** [comment]
@xhochy 
Hi Uwe, 
Does this mean it is working, cancelled, or tracked somewhere else?

**Pull request closed without merging**
