### PR TITLE
tensorflow 2.18.0-rc1

### PR DESCRIPTION
**Pull request by xhochy**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xhochy** [comment]
Theoretically this support NumPy 2 and Python 3.13 but we first need to migrate `h5py`.

**Comment by xhochy** [comment]
Python 3.13 depends on https://github.com/conda-forge/h5py-feedstock/pull/148

**Comment by hmaarrfk** [comment]
Does building complete?

I'm wondering if we can at least add a test to stay aware of things like:
https://github.com/conda-forge/tensorflow-feedstock/issues/296#issuecomment-2421179700

**Comment by xhochy** [comment]
> Does building complete?

For the non-CUDA variants, it works. I have cancelled the jobs as I realised that the CUDA jobs just hang at the `./configure` step and would only be a waste of resource. I now what has to be fixed with CUDA to compile (same fixes as in jaxlib) but I'll probably do them next week. 

Is there anything in https://github.com/conda-forge/tensorflow-feedstock/issues/296#issuecomment-2421179700 which we could test on a non-CUDA system?

**Comment by hmaarrfk** [comment]
> same fixes as in jaxlib

I really tried hard to read your comments on the jax repo to see if it was something I could fix myself.

> Is there anything in https://github.com/conda-forge/tensorflow-feedstock/issues/296#issuecomment-2421179700 which we could test on a non-CUDA system?

I was hoping we could "force" some compilation (but not execution). That said I don't know enough about the workings of tensorflow for this.

**Comment by h-vetinari** [comment]
> Python 3.13 depends on [conda-forge/h5py-feedstock#148](https://github.com/conda-forge/h5py-feedstock/pull/148)

AFAIR 2.18 is also the first version to support numpy 2.0

**Comment by xhochy** [comment]
I have both added locally and will push them with some fixes in the next days. If anyone is eager to be faster, happy to see it but let me know 🙃

**Comment by hmaarrfk** [comment]
would you be willing to push your fixes? curious if we can get the protobuf going with 2.18.0 now that it is release.

**Pull request closed without merging**
