### PR TITLE
Protobuf320 and GRPC migration

### PR DESCRIPTION
**Pull request by hmaarrfk**
Closes https://github.com/conda-forge/tensorflow-feedstock/pull/232
Closes https://github.com/conda-forge/tensorflow-feedstock/pull/228

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
This compiles fine for linux CPU. Time to check CPU + CUDA 11.2 before running a full suite of builds.

**Comment by hmaarrfk** [comment]
Dear xhochy,

This seems to be passing with linux both without cuda, and with cuda 11.2. I'm starting to build out linux, but if you could build out osx that would be greatly appreciated

**Comment by xhochy** [comment]
@hmaarrfk I'm nearly done with #205 (i.e. only CUDA 10.2 is missing). I would prefer to merge that first and then rebase.

**Comment by xhochy** [comment]
If you really want this PR, then we should merge it to a 2.7.x branch.

**Comment by hmaarrfk** [comment]
lets finish 205 first.

**Comment by ngam** [comment]
Sorry to jump in out of nowhere, please consider adding the xla option and cpu_count from my otherwise useless PR in #235, both are innocent additions with little consequences. Then we can skip building 2.8.1 entirely (it is only security fixes, but you're welcome to simply swap 2.8.1 for 2.8.0 in PR #205)

**Comment by ngam** [comment]
Happy to initiate a PR for 2.9.0 in a week if not

**Comment by hmaarrfk** [comment]
I think the outputs of #205 are likely set in stone since xhochy is quite deep in the build process (it takes 2-3 days on a single large machine of mine to build this so it isn't the easiest thing to build).

However, if you create a checklist then we have a list of fixes that we won't forget.

**Comment by hmaarrfk** [comment]
didn't know 2.9.0 was coming out, we just got a handle on 2.8 :D

**Comment by ngam** [comment]
> I think the outputs of #205 are likely set in stone since xhochy is quite deep in the build process (it takes 2-3 days on a single large machine of mine to build this so it isn't the easiest thing to build).
> 
> However, if you create a checklist then we have a list of fixes that we won't forget.

Yes, I understand, I will make a checklist and we will include those in the 2.9.x builds :)

For future reference, I can build tensorflow 2.8.x cuda112 in under 1 hour (using my experimental conda-smithy with singularity), but it is a little tricky as I need to babysit the machine. Happy to shoulder some builds. I can also likely shoulder some osx builds in the near future. I hate to repeat this, but I also really don't want you two to shoulder all the build all the time!

**Comment by ngam** [comment]
> didn't know 2.9.0 was coming out, we just got a handle on 2.8 :D

2.9 is days away (they've just release the patches for 2.6, 2.7, and 2.8) 🥵

**Pull request closed without merging**
