### PR TITLE
add FernandezMathieu to maintainer list

### PR DESCRIPTION
**Pull request by FernandezMathieu**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by 183amir** [comment]
Hi @FernandezMathieu thank you for your interest in becoming a maintainer of the conda-forge tensorflow package. Usually, we add people as maintainers during their first contribution. Did you have something in mind when you added yourself to the list here?

**Comment by njzjz** [comment]
Please add `[ci skip] [skip ci]` to your commit message, if you do not do any other changes.

**Comment by FernandezMathieu** [comment]
Hi @183amir, to be honest it just to upgrade the tensorflow version. But i create this PR without seeing the [drafted one](https://github.com/conda-forge/tensorflow-feedstock/pull/104). Anyway, i will just follow the PR and wait. Thanks.

**Comment by 183amir** [comment]
@FernandezMathieu if you have a working recipe, please open another PR. That one is not being progressed anymore.

**Pull request closed without merging**
