### PR TITLE
Icu73 migration

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
might need to hold back the protobuf stuff. I'm trying to keep this migration "simple".

**Comment by hmaarrfk** [comment]
this is progressing fine locally for cuda. any objections to merging wen completed?

**Comment by h-vetinari** [comment]
> this is progressing fine locally for cuda. any objections to merging when completed?

I thought @xhochy had gotten quite far with #329, but perhaps we need to drop the protobuf upgrade (but could keep the rest?).

**Comment by hmaarrfk** [comment]
i don't think it works with either the current protobuf or the old protobuf.

I've been trying to build his branches periodically, the latest ones don't work.

**Comment by hmaarrfk** [comment]
Closing in favor of #338

**Comment by xhochy** [comment]
> i don't think it works with either the current protobuf or the old protobuf.
> 
> I've been trying to build his branches periodically, the latest ones don't work.

No, I have not found any combination of nvcc that works for any Protobuf release for 2.13.x. I will invest a bit in 2.14 but otherwise we probably need to run a git bisect to find the cause for the issues.

**Pull request closed without merging**
