### PR TITLE
tensorflow 1.5.0

### PR DESCRIPTION
**Pull request by peterjc**
I am hoping this will fix issue #49 

Updated dependencies as per listing on PyPI: https://pypi.python.org/pypi/tensorflow/1.5.0

Note compared to the list for v1.4.0, there is a new dependency: ``absl-py (>=0.1.6)``

However, absl-py does not yet seem to be on conda.

### CODE REVIEW

**Comment by peterjc** [comment]
We'll need to update https://github.com/conda-forge/tensorboard-feedstock first

**Comment by jjhelmus** [comment]
absl-py 0.1.10 recipe submitted to staged-recipes, conda-forge/staged-recipes#5065.

**Comment by dhirschfeld** [comment]
Tried to update the `tensorboard` dependency over at https://github.com/conda-forge/tensorboard-feedstock/pull/4 but a couple of the appveyor builds are failing and I've no idea why.

**Comment by dhirschfeld** [comment]
Will re-render since the deps should now be available and the appveyor error seems to be the same `The batch file cannot be found` as for the `tensorboard` recipe

**Comment by dhirschfeld** [comment]
@conda-forge-admin, please rerender

**Comment by dhirschfeld** [comment]
Woohoo! If no one objects (or beats me to it) I'll merge this shortly...

**Pull request merged**
