### PR TITLE
Update to 1.4.0

### PR DESCRIPTION
**Pull request by dhirschfeld**
Is this all that's required?

### CODE REVIEW

**Comment by dhirschfeld** [comment]
Looks like the Travis py27 build failed with:
```
ImportError: No module named enum
```

**Comment by hajapy** [comment]
It seems this is now required in 1.4 for py<34

https://github.com/tensorflow/tensorflow/blob/v1.4.0/tensorflow/tools/pip_package/setup.py#L35

It is used here: 
https://github.com/tensorflow/tensorflow/blob/v1.4.0/tensorflow/python/ops/variable_scope.py#L24

Since the import test is skipped for linux and windows py27 is not built, only travis (os x) shows the error but it would be an issue with for linux as well.

**Comment by hajapy** [comment]
I would also add that a number of the required run time dependencies are outdated as compared to the setup.py linked above (a few are related to tensorboard which is not bundled in the wheel anymore). 

When https://github.com/conda-forge/staged-recipes/pull/3866 is done we can update the run requirements to include tensorboard.

**Comment by jerowe** [comment]
I didn't even see this and naively opened a PR for 1.4. ;-)

How is the progress on this? The newest tensorflow/models repo says it needs 1.4, and I would like to upgrade my env.

**Comment by hajapy** [comment]
@dhirschfeld think you will come back to wrapping this up?

**Comment by dhirschfeld** [comment]
@hajapy - I gave it a go, we'll see what the CI thinks...

**Comment by hajapy** [comment]
Awesome, thanks! Looks like CI is happy. I still think we should remove all the tensorboard only run dependencies as those are already part of the tensorboard recipe. After that change, will be ready for merge!

**Comment by dhirschfeld** [comment]
I won't have time to get to this until Friday now so feel free to edit & push to my branch if you want...

**Comment by hajapy** [comment]
@dhirschfeld https://github.com/dhirschfeld/tensorflow-feedstock/pull/1

**Comment by hajapy** [comment]
ping @conda-forge/core could someone please merge this?

**Comment by danielfrg** [comment]
Thanks for the update!

**Pull request merged**
