### PR TITLE
Bump to 2.12

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
See some prior conversation in https://github.com/conda-forge/tensorflow-feedstock/pull/301

**Comment by Tobias-Fischer** [comment]
Seems like we are still stuck with
```
ERROR: /home/conda/feedstock_root/build_artifacts/tensorflow-split_1679950454577/work/tensorflow/compiler/xla/BUILD:83:17: no such target '@com_google_protobuf//:well_known_types_py_pb2_genproto': target 'well_known_types_py_pb2_genproto' not declared in package '' defined by /home/conda/feedstock_root/build_artifacts/tensorflow-split_1679950454577/_build_env/share/bazel/e5d29df473be7f8cf01cf24df4262363/external/com_google_protobuf/BUILD.bazel and referenced by '//tensorflow/compiler/xla:xla_data_proto_py_genproto'
```

**Comment by hmaarrfk** [comment]
is this the same failure as before?

**Comment by Tobias-Fischer** [comment]
Yep ..

**Comment by Tobias-Fischer** [comment]
There is no rush from my side (and very limited time to spend on this - apologies). Please feel free to take over the PR / start a new one once you are back with proper access @ngam @hmaarrfk

**Comment by Tobias-Fischer** [comment]
> 2.13 will be out in a month anyway

Are the problems we encounter in this PR likely going away with 2.13?

**Comment by sh-shahrokhi** [comment]
> > 2.13 will be out in a month anyway
> 
> Are the problems we encounter in this PR likely going away with 2.13?

I could not find anything but you may want to check the release notes: 
https://github.com/tensorflow/tensorflow/blob/r2.13/RELEASE.md

**Comment by njzjz** [comment]
> we should revert this commit and test next [tensorflow/tensorflow@84f4092](https://github.com/tensorflow/tensorflow/commit/84f40925e929d05e72ab9234e53c729224e3af38)

We need a patch to remove this line:

https://github.com/tensorflow/tensorflow/blob/0db597d0d758aba578783b5bf46c889700a45085/tensorflow/tsl/platform/default/build_config.bzl#L408-L409

**Comment by njzjz** [comment]
I don't find a workaround to resolve this error:
```
ERROR: /home/conda/feedstock_root/build_artifacts/tensorflow-split_1684490216303/work/tensorflow/c/BUILD:359:11: Compiling tensorflow/c/tf_status.cc failed: (Exit 1): x86_64-conda-linux-gnu-cc failed: error executing command 
  (cd /home/conda/feedstock_root/build_artifacts/tensorflow-split_1684490216303/_build_env/share/bazel/07f14a670c6615d0600f0f6296f25be0/execroot/org_tensorflow && \
  exec env - \
    PATH=/home/conda/feedstock_root/build_artifacts/tensorflow-split_1684490216303/work:/home/conda/feedstock_root/build_artifacts/tensorflow-split_1684490216303/_build_env/bin:/home/conda/feedstock_root/build_artifacts/tensorflow-split_1684490216303/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin:/opt/conda/condabin:/home/conda/feedstock_root/build_artifacts/tensorflow-split_1684490216303/_build_env/bin:/home/conda/feedstock_root/build_artifacts/tensorflow-split_1684490216303/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin:/opt/conda/bin:/opt/conda/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/conda/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/home/conda/feedstock_root/build_artifacts/tensorflow-split_1684490216303/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python \
    PYTHON_LIB_PATH=/home/conda/feedstock_root/build_artifacts/tensorflow-split_1684490216303/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.10/site-packages \
    TF2_BEHAVIOR=1 \
    TF_SYSTEM_LIBS=absl_py,astor_archive,astunparse_archive,boringssl,com_github_googlecloudplatform_google_cloud_cpp,com_github_grpc_grpc,com_google_protobuf,curl,cython,dill_archive,flatbuffers,gast_archive,gif,icu,libjpeg_turbo,org_sqlite,png,pybind11,snappy,zlib \
  /home/conda/feedstock_root/build_artifacts/tensorflow-split_1684490216303/_build_env/bin/x86_64-conda-linux-gnu-cc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/k8-opt/bin/tensorflow/c/_objs/tf_status/tf_status.pic.d '-frandom-seed=bazel-out/k8-opt/bin/tensorflow/c/_objs/tf_status/tf_status.pic.o' -fPIC -DEIGEN_MPL2_ONLY '-DEIGEN_MAX_ALIGN_BYTES=64' -iquote . -iquote bazel-out/k8-opt/bin -iquote external/eigen_archive -iquote bazel-out/k8-opt/bin/external/eigen_archive -iquote external/com_google_absl -iquote bazel-out/k8-opt/bin/external/com_google_absl -iquote external/nsync -iquote bazel-out/k8-opt/bin/external/nsync -iquote external/double_conversion -iquote bazel-out/k8-opt/bin/external/double_conversion -iquote external/com_google_protobuf -iquote bazel-out/k8-opt/bin/external/com_google_protobuf -iquote external/gif -iquote bazel-out/k8-opt/bin/external/gif -iquote external/libjpeg_turbo -iquote bazel-out/k8-opt/bin/external/libjpeg_turbo -iquote external/com_googlesource_code_re2 -iquote bazel-out/k8-opt/bin/external/com_googlesource_code_re2 -iquote external/farmhash_archive -iquote bazel-out/k8-opt/bin/external/farmhash_archive -iquote external/fft2d -iquote bazel-out/k8-opt/bin/external/fft2d -iquote external/highwayhash -iquote bazel-out/k8-opt/bin/external/highwayhash -iquote external/zlib -iquote bazel-out/k8-opt/bin/external/zlib -isystem third_party/eigen3/mkl_include -isystem bazel-out/k8-opt/bin/third_party/eigen3/mkl_include -isystem external/eigen_archive -isystem bazel-out/k8-opt/bin/external/eigen_archive -isystem external/nsync/public -isystem bazel-out/k8-opt/bin/external/nsync/public -isystem external/farmhash_archive/src -isystem bazel-out/k8-opt/bin/external/farmhash_archive/src -Wno-all -Wno-extra -Wno-deprecated -Wno-deprecated-declarations -Wno-ignored-attributes -Wno-array-bounds -Wunused-result '-Werror=unused-result' -Wswitch '-Werror=switch' '-Wno-error=unused-but-set-variable' -DAUTOLOAD_DYNAMIC_KERNELS '-std=c++17' -DEIGEN_AVOID_STL_ARRAY -Iexternal/gemmlowp -Wno-sign-compare '-ftemplate-depth=900' -fno-exceptions -DINTEL_MKL -DAMD_ZENDNN -msse3 -pthread -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c tensorflow/c/tf_status.cc -o bazel-out/k8-opt/bin/tensorflow/c/_objs/tf_status/tf_status.pic.o)
# Configuration: 311988e8e1d0b6f908e732a2a226b7c4c672bd3781cfe926d0de72cee0e8a023
# Execution platform: @local_execution_config_platform//:platform
In file included from ./tensorflow/tsl/platform/status.h:37,
                 from ./tensorflow/tsl/c/tsl_status_internal.h:19,
                 from ./tensorflow/c/tf_status_internal.h:19,
                 from tensorflow/c/tf_status.cc:18:
bazel-out/k8-opt/bin/tensorflow/tsl/protobuf/error_codes.pb.h:10:10: fatal error: google/protobuf/port_def.inc: No such file or directory
   10 | #include <google/protobuf/port_def.inc>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by sh-shahrokhi** [comment]
protubuf requirement is changed in TF 2.12. maybe this caused the problem?

**Comment by sh-shahrokhi** [comment]
> @sh-shahrokhi we are using libprotobuf 3.21

I see this in the CI log:
`    protobuf:                  4.21.12-py39h227be39_0       conda-forge
`

**Comment by h-vetinari** [comment]
Protobuf has a weird version scheme starting from v3.21==v4.21. Basically the minor version becomes the "protbuf" version, and the major version (per language bindings) indicates whether there are breaking changes. Which is why libprotobuf (C++) 3.21 goes together with protobuf (python) 4.21.

**Comment by h-vetinari** [comment]
> I don't find a workaround to resolve this error:
> 
> ```
> [...]
> bazel-out/k8-opt/bin/tensorflow/tsl/protobuf/error_codes.pb.h:10:10: fatal error: google/protobuf/port_def.inc: No such file or directory
>    10 | #include <google/protobuf/port_def.inc>
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> ```

That file is definitely [there](https://github.com/regro/libcfgraph/blob/master/artifacts/libprotobuf/conda-forge/linux-64/libprotobuf-3.21.12-h3eb15da_0.json#L318) if we point to our `$PREFIX/include` path correctly.

**Comment by njzjz** [comment]
I asked in the TensorFlow repository at https://github.com/tensorflow/tensorflow/issues/60667#issuecomment-1568783478, but they refused to provide support and bugfix for systemlibs.

**Comment by h-vetinari** [comment]
I'm against vendoring protobuf. Not strongly enough to block progress here (we haven't had builds in a while, and protobuf is a pain in many ways), but I think it's the wrong approach.

**Comment by xhochy** [comment]
I have an alternative branch over at https://github.com/conda-forge/tensorflow-feedstock/pull/323 that has 80% build locally. If it succeeds, I can do the full matrix.

**Comment by hmaarrfk** [comment]
shall we close this https://github.com/conda-forge/tensorflow-feedstock/pull/325

**Comment by jakirkham** [comment]
Should this be closed now that PR ( https://github.com/conda-forge/tensorflow-feedstock/pull/325 ) has landed?

**Pull request closed without merging**
