### PR TITLE
Build tensorflow 1.2.1 from source on Linux

### PR DESCRIPTION
**Pull request by jjhelmus**

### CODE REVIEW

**Comment by jjhelmus** [comment]
It looks like building Tensorflow from source is going to take longer than the available CI time on Circle CI.  Unless others have ideas on how to work around this limitation, I think repacking the wheel files is the best option.

**Comment by jakirkham** [comment]
Are you sure? It looks like it ran for an hour and then Bazel crashed. 😕

**Comment by jjhelmus** [comment]
From the log I though that Circle CI had killed the build because of the time.  The portion of the log where this is occurring is: 

```
      Scheduling:
        Compiling tensorflow/core/kernels/cwise_op_asin.cc, 964 s
        Compiling tensorflow/core/kernels/cwise_op_imag.cc, 955 s
        Compiling tensorflow/core/kernels/cwise_op_exp.cc, 947 s
        Compiling tensorflow/core/kernels/cwise_op_rint.cc, 937 s
        Compiling tensorflow/core/kernels/cwise_op_acos.cc, 935 s
        Compiling tensorflow/core/kernels/cwise_op_tanh.cc, 929 s
        Compiling tensorflow/core/kernels/cwise_op_rsqrt.cc, 929 s
        Compiling tensorflow/core/kernels/cwise_op_isnan.cc, 920 s
        Compiling tensorflow/core/kernels/cwise_op_mul_2.cc, 915 s
        ... 150 more jobs
/feedstock_root/build_artefacts/tensorflow_1500050163798/work/tensorflow-1.2.1/conda_build.sh: line 25:   265 Killed                  bazel ${BAZEL_OPTS} build --config=opt //tensorflow/tools/pip_package:build_pip_package
```

Is this not how a timeout appears?  I have not seen enough of this type of behavior to know for sure.

**Comment by jakirkham** [comment]
Nope. Normally it is pretty clear and says something like build exceeded time limit. It also is pretty good about putting this on one line. Also, the CircleCI time limit is 2hrs and this only ran for 1hr.

**Comment by jjhelmus** [comment]
> Nope. Normally it is pretty clear and says something like build exceeded time limit.

Good to know.  The `Killed` must be coming from Bazel itself then.  I know in the past allowing bazel to use the default number of jobs caused some memory issues.  I'll try limited the jobs to two and see if that helps.

**Comment by jakirkham** [comment]
Also if we are able to get this to build on CircleCI and there is concern about how to handle the other Python versions, we can solve that with CircleCI matrix support ( https://github.com/conda-forge/conda-smithy/pull/532 ).

**Comment by jjhelmus** [comment]
Woohoo, this passed.  Takes 1 hour 22 minutes but the import now works on CentOS 6.  
@jakirkham CircleCI matrix sounds like a good solution to building for the three Python versions.  Much better than the idea I have of having three branches.

**Comment by jakirkham** [comment]
Sweet! Glad to hear that worked. Though I guess that means Mac source builds are out of the question.

Yeah the CircleCI matrix builds are based on a new version of CircleCI. It was in beta, but I think it is officially released now. Saw an email to that regard in the past couple weeks. There are a few examples linked in that PR. Should give you a better feel for how it would look.

**Comment by jjhelmus** [comment]
@jakirkham I have not looked into CirclCI matrix builds.  Do you have an example workflow for this that you could share?

**Comment by jakirkham** [comment]
It's in `conda-smithy`'s `master`, but is not released yet. If one uninstalls `conda-smithy` from `root` and does a development install of `conda-smithy`'s `master` branch with `pip` into `root` (e.g. `--no-deps -e <path to conda-smithy>`), they can re-render with this feature.

**Comment by jakirkham** [comment]
So `conda-smithy` 2.3.3 has matrix support for CircleCI, which can now be used. Also looks like this has some merge conflicts.

**Comment by jjhelmus** [comment]
Not that Tensorflow 1.3.0 is out this build it outdated.  I hope to have some time to try building the new version from source this week.

**Comment by sdvillal** [comment]
@jjhelmus Based on your good work, I have a work in progress, but functional recipe for 1.3.0 [here](https://github.com/loopbio/tensorflow-feedstock/tree/master/recipe) - some preliminary packages [in my channel](https://anaconda.org/sdvillal). I "just" need to make all the test pass, but won't have time this week to finish it. In any case, it is a GPU build against MKL and enabling XLA and jemalloc (so for conda-forge it should prove even smoother). I can give a hand if you need something to roll out the conda-forge version.

**Pull request closed without merging**
