### PR TITLE
WIP: Update to version 0.12.0rc0 with Windows support

### PR DESCRIPTION
**Pull request by jjhelmus**

### CODE REVIEW

**Comment by jjhelmus** [comment]
WIP (Work in progress) as protobuf 3.1.0 is required by this package but not available yet in `conda-forge`.  Submitting here to test the build so far.  Will submit an update to conda-forge/protobuf-feedstock shortly to bump the recipe to 3.1.0.

**Comment by ghego** [comment]
@jjhelmus Nice! Was about to open a similar PR :) Lmk if you need help testing it. Btw the most recent `conda-smithy` is v1.6.1

**Comment by babhishek21** [comment]
This PR is now obsolete, I think. This should be closed in light of #26 .

**Comment by jjhelmus** [comment]
> This should be closed in light of #26 .

Agreed.

**Pull request closed without merging**
