### PR TITLE
WIP: Just try to rebuild the old stuff the exact same way as we did before.

### LINKED ISSUE #225: @conda-forge-admin please rerender
### Additional comment:

_No response_

### PR DESCRIPTION
**Pull request by conda-forge-linter**
hmaarrfk: I'm trying to rebuild this exactly as we had it in the first build. For some reason, it is giving me real trouble.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@jakirkham did anything change in the cuda images? I can't seem to build this feedstock again, with what I believe are the the same settings as last time.

**Comment by ngam** [comment]
> @jakirkham did anything change in the cuda images? I can't seem to build this feedstock again, with what I believe are the the same settings as last time.

Also copying @leofang and @kkraus14 who were helpful in discussing the cuda override issue.

@hmaarrfk if it's not a hassle, could you please put the error you get in the comments? Thanks for working on this!!

**Comment by ngam** [comment]
(as in, are they the same as in the logs here or are they different?)

**Comment by hmaarrfk** [comment]
A few packages are the same, but I didn't rerender :/ I can try to pin packages a little harder, but that is more time than I have for today.

**Comment by ngam** [comment]
:/ sorry this is turning into a nightmare :/

**Comment by kkraus14** [comment]
> @jakirkham did anything change in the cuda images? I can't seem to build this feedstock again, with what I believe are the the same settings as last time.

The only thing that I know of that have changed recently is a PR I pushed of changing the CUDA headers to be system includes instead of user includes: https://github.com/conda-forge/nvcc-feedstock/pull/80

You could try pinning to the previous build of `nvcc_linux-64` to see if that resolves your issue. That being said, if that fixes your issue that's pointing towards something problematic in the build here.

**Comment by hmaarrfk** [comment]
Ok. That might actually be the issue. It says we aren't depending on the right things

**Comment by hmaarrfk** [comment]
THank you @kkraus14 reverting that that seemed to work. Now I think xhochy  is smarter than me and may have found a better way. So i'm going to try his fix too.

**Comment by ngam** [comment]
@hmaarrfk are we all good now?

Btw, do you have any thoughts on enabling xla and including (if not already) the nvcc compiler as a runtime dep? (ref #223)

**Pull request closed without merging**
