### PR TITLE
Update 2.8.0

### PR DESCRIPTION
**Pull request by ganand1**
Checklist
* [ x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngam** [comment]
@ganand1, I don't mean to discourage you here, but please wait a little. Some of the most experienced people in conda-forge are working on releasing 2.7.0. Once that's done, you can try 2.8.0. Tensorflow is essentially one of the hardest packages out of the 15,000+ ones we have. Believe me, I would very much like to see things move faster, but it is just difficult.

If you have particular/urgent needs for now, I am happy to offer my advice on how to get an environment set up with the latest tensorflow and/or build this locally.

**Comment by ganand1** [comment]
> @ganand1, I don't mean to discourage you here, but please wait a little. Some of the most experienced people in conda-forge are working on releasing 2.7.0. Once that's done, you can try 2.8.0. Tensorflow is essentially one of the hardest packages out of the 15,000+ ones we have. Believe me, I would very much like to see things move faster, but it is just difficult.
> 
> If you have particular/urgent needs for now, I am happy to offer my advice on how to get an environment set up with the latest tensorflow and/or build this locally.

sure @ngam  .Will leave this on hold for now. 
Please share how to build locally. Greatly appreciate it. I am using python build-locally.py <config> but i am repeatedly getting connection timed out within the docker while those packages are getting downloaded. But on the local machine able to download the same tar.gz files.

**Comment by hmaarrfk** [comment]
@ganand1 do not get discouraged regarding building 2.8.0

I do suggest starting from the work we have done in:
https://github.com/conda-forge/tensorflow-feedstock/pull/189/commits

Many people have helped get it to that stage.

Good luck! It takes a while to build tensorflow.

If you are trying to USE tensorflow today, you will likely want to download it from an other source

**Comment by ngam** [comment]
> Please share how to build locally

what type of machine(s) do you have locally?

Usually, python build-locally.py works fine. See hmaarrfk's notes here: https://github.com/conda-forge/tensorflow-feedstock/blob/9d76035c6a6e928ac87500cbbc10f9af160dd760/recipe/README.md. But essentially, you want to target the platform you have locally --- for example, if you have a linux running on an x86_64 machine, then you should build linux64. If you have an M1 MacOS, then you should build osx-arm64. Otherwise, things will take forever. (Note that for MacOS, you don't use Docker, but you still should use `python build-locally.py`.) If you are on Windows, I have no idea what would be best, but maybe WSL?

Now, since the work in that #189 is nearing the finish, you can start by bumping the version from the final commit there and start a new PR (or pull it in to here). Then you (and people here) can help figure out details as you go. For reference, I was able to build tensorflow 2.7.0 all the way back almost three months ago on my osx-arm64: https://anaconda.org/ngam/tensorflow/files. However, even on a relatively powerful machine, building tensorflow was the first time my M1 Max got crippled lol --- it finished within half an hour though, if I remember correctly. In that case, I built using `mamba build .` (in the root of the repo). You can use `mamba build recipe` or `conda build recipe` if you have `mamba` and `boa` or `conda` and `conda-build` respectively. Note however, building directly like that may not translate to success on the CI because your system may have newer compilers, etc.

I have had good luck using tensorflow from PyPI within a conda environment for a while mainly because the Apple-optimized Tensorflow is only available on PyPI (https://developer.apple.com/metal/tensorflow-plugin/). Recently, I tested tensorflow-gpu 2.7.0, 2.7.1, and 2.8.0 on a linux machine and things worked totally fine (for the GPU part, you need to expose the cuda paths, either by loading cudatoolkit and cudnn if you are on an HPC or by linking directly by setting something like `export LD_LIBRARY_PATH=$CONDA_PREFIX/lib` --- note this approach may break certain things like ssh if you're on a fedora-like system because the openssl from conda-forge lacks certain parameters). For what it is worth, if you are on an Intel machine, you may be interested in using their own distributions of tensorflow (note though the one on conda-forge is still stuck at 2.6.0 while the one on PyPI is at 2.7.0; see more in the link below --- I personally didn't notice any usefulness when using Intel's tensorflow, but I don't know, it may be useful for you. They have specific distributions like tensorflow-avx512 as well if you're interested, which will break if the machine doesn't support avx512, see more here https://pypi.org/project/intel-tensorflow-avx512/).

https://www.intel.com/content/www/us/en/developer/articles/guide/optimization-for-tensorflow-installation-guide.html

> repeatedly getting connection timed out within the docker while those packages are getting downloaded. But on the local machine able to download the same tar.gz files 

I believe this is often due to a mismatch in the platform. In my experience, it takes significantly longer when the platform is different, e.g. linux64 and aarch64.



Finally, some tips:

- you can always disable runs you don't care about in the CI here: `skip: true  # [win]` is the line of interest
- remember to rerender whenever you make substantial changes (`@conda-forge-admin, please rerender` here or `mamba smithy rerender`/`conda smithy rerender` locally, note you will need `conda-smithy` installed in your env)
- if you are generally interested in getting involved in this community, you should check out conda-forge/staged-recipes and other places; I am personally quite new to all of this and I have found that most people are generous and helpful like hmaarrfk. This is a relatively difficult package to build, but feel free to keep trying; I would build upon the previous PR (#189) though
- an important reference for this particular package is this file upstream: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/pip_package

**Comment by ganand1** [comment]
thank you @ngam  really useful tips . Thanks for sharing

i use linux-64 and run
python build-locally.py linux_64_c_compiler_version9cuda_compiler_versionNonecudnnundefinedcxx_compiler_version9python3.9.____cpython

dont see a platform mismatch for the connectivity issue. This is really preventing me from checking out locally.

**Comment by ngam** [comment]
> python build-locally.py linux_64_c_compiler_version9cuda_compiler_versionNonecudnnundefinedcxx_compiler_version9python3.9.____cpython

When I run this command in this PR on a linux machine, I get this: https://gist.github.com/ngam/0aaf531709767165f354d9a0ce6bbdd2

**Comment by ngam** [comment]
Can you please try to pull in everything in PR #189 up to commit f10ef544d12c5cde4e4cd16655f12fe200449c5d?

**Comment by ngam** [comment]
This is what happens if I run `python build-locally.py linux_64_c_compiler_version9cuda_compiler_versionNonecudnnundefinedcxx_compiler_version9numpy1.19python3.9.____cpython` in the other PR. I terminated the process, otherwise it was building fine

https://gist.github.com/681f7a785cd34c0730468aff2ee17482

**Pull request closed without merging**
