### PR TITLE
2.15.0 for libgrpc159_libprotobuf4244

### PR DESCRIPTION
**Pull request by xhochy**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by h-vetinari** [comment]
Thanks for tackling this! You might want to pull in #359 directly

**Comment by xhochy** [comment]
@conda-forge/tensorflow All builds passed on `linux-64` and one on `osx-64`. I will start the remaining `osx-*` builds this afternoon.

**Comment by h-vetinari** [comment]
Amazing news! 🥳

**Comment by xhochy** [comment]
@h-vetinari @hmaarrfk Builds are on the `uwe.korn-tf-gpu` and `uwe.korn-tf-experimental` channels again. 

Logs:

- [linux-64-logs.zip](https://github.com/conda-forge/tensorflow-feedstock/files/13739279/linux-64-logs.zip)
- [osx-arm64-logs.zip](https://github.com/conda-forge/tensorflow-feedstock/files/13739283/osx-arm64-logs.zip)

**Comment by h-vetinari** [comment]
This is the first time I'm trying to do a CFEP-03 copy... I looked at the build logs and noted a few minor things, that have to be pre-existing (given the changes here):
```
WARNING: Exact overlap between include/tensorflow/core/platform/ctstring.h in packages libtensorflow_cc and libtensorflow
WARNING: Exact overlap between include/tensorflow/core/platform/ctstring_internal.h in packages libtensorflow_cc and libtensorflow
WARNING: Exact overlap between include/tsl/c/tsl_status.h in packages libtensorflow_cc and libtensorflow
WARNING: Exact overlap between include/tsl/platform/ctstring.h in packages libtensorflow_cc and libtensorflow
WARNING: Exact overlap between include/tsl/platform/ctstring_internal.h in packages libtensorflow_cc and libtensorflow
WARNING: Exact overlap between lib/libtensorflow_framework.2.15.0.dylib in packages libtensorflow_cc and libtensorflow
WARNING: Exact overlap between lib/libtensorflow_framework.2.dylib in packages libtensorflow_cc and libtensorflow
WARNING: Exact overlap between lib/libtensorflow_framework.dylib in packages libtensorflow_cc and libtensorflow
```

Also why are we putting a patch (that conda patches again) into `$PREFIX/include`? Seems very strange
```
include/third_party/pybind11_protobuf/0001-Add-Python-include-path.patch (text): Patching
```

In any case, I wanted to copy the packages, but I haven't managed to run the [commands](https://github.com/conda-forge/tensorflow-feedstock/pull/347#issuecomment-1809390975), because I cannot pass through authentication of the anaconda client. I have an account, I double-checked (then updated) my password, I've tried various ways to spell my identity (username/email), and I haven't managed to get through yet.

**Comment by hmaarrfk** [comment]
hmmm ok i got it to work for me. I use my username

**Pull request merged**
