### PR TITLE
1.14.0

### PR DESCRIPTION
**Pull request by brendanf**
Checklist
* [X] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

Although I see that work is ongoing for even newer versions of TensorFlow, I am trying to build a package that specifically requires 1.14, so I've carried on with some modifications to hopefully get #93 working on all platforms.

### CODE REVIEW

**Comment by brendanf** [comment]
@conda-forge-admin, please rerender

**Comment by brendanf** [comment]
```
ERROR: /home/conda/feedstock_root/build_artifacts/tensorflow_1594315493966/work/tensorflow/compiler/xla/service/cpu/BUILD:449:1: C++ compilation of rule '//tensorflow/compiler/xla/service/cpu:disassembler' failed (Exit 1): x86_64-conda_cos6-linux-gnu-cc failed: error executing command 
  (cd /home/conda/.cache/bazel/_bazel_conda/081b1149059792786b07e8feda0ce6f8/execroot/org_tensorflow && \
  exec env - \
    PATH=/home/conda/feedstock_root/build_artifacts/tensorflow_1594315493966/work:/home/conda/feedstock_root/build_artifacts/tensorflow_1594315493966/_build_env/bin:/home/conda/feedstock_root/build_artifacts/tensorflow_1594315493966/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin:/opt/conda/condabin:/home/conda/feedstock_root/build_artifacts/tensorflow_1594315493966/_build_env:/home/conda/feedstock_root/build_artifacts/tensorflow_1594315493966/_build_env/bin:/home/conda/feedstock_root/build_artifacts/tensorflow_1594315493966/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_:/home/conda/feedstock_root/build_artifacts/tensorflow_1594315493966/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin:/opt/conda/bin:/opt/conda/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/conda/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/home/conda/feedstock_root/build_artifacts/tensorflow_1594315493966/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python \
    PYTHON_LIB_PATH=/home/conda/feedstock_root/build_artifacts/tensorflow_1594315493966/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.7/site-packages \
    TF_CONFIGURE_IOS=0 \
    TF_DOWNLOAD_CLANG=0 \
    TF_NEED_CUDA=0 \
    TF_NEED_OPENCL_SYCL=0 \
    TF_NEED_ROCM=0 \
    TF_SYSTEM_LIBS=curl,llvm,nsync,zlib_archive \
  /home/conda/feedstock_root/build_artifacts/tensorflow_1594315493966/work/x86_64-conda_cos6-linux-gnu-cc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/k8-opt/bin/tensorflow/compiler/xla/service/cpu/_objs/disassembler/disassembler.pic.d '-frandom-seed=bazel-out/k8-opt/bin/tensorflow/compiler/xla/service/cpu/_objs/disassembler/disassembler.pic.o' -fPIC -D__CLANG_SUPPORT_DYN_ANNOTATION__ -DEIGEN_MPL2_ONLY '-DEIGEN_MAX_ALIGN_BYTES=64' '-DEIGEN_HAS_TYPE_TRAITS=0' -DTF_USE_SNAPPY -D_DEBUG -DLLVM_ENABLE_STATS -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DLLVM_BUILD_GLOBAL_ISEL -iquote . -iquote bazel-out/k8-opt/genfiles -iquote bazel-out/k8-opt/bin -iquote external/com_google_absl -iquote bazel-out/k8-opt/genfiles/external/com_google_absl -iquote bazel-out/k8-opt/bin/external/com_google_absl -iquote external/nsync -iquote bazel-out/k8-opt/genfiles/external/nsync -iquote bazel-out/k8-opt/bin/external/nsync -iquote external/eigen_archive -iquote bazel-out/k8-opt/genfiles/external/eigen_archive -iquote bazel-out/k8-opt/bin/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/k8-opt/genfiles/external/local_config_sycl -iquote bazel-out/k8-opt/bin/external/local_config_sycl -iquote external/gif_archive -iquote bazel-out/k8-opt/genfiles/external/gif_archive -iquote bazel-out/k8-opt/bin/external/gif_archive -iquote external/jpeg -iquote bazel-out/k8-opt/genfiles/external/jpeg -iquote bazel-out/k8-opt/bin/external/jpeg -iquote external/protobuf_archive -iquote bazel-out/k8-opt/genfiles/external/protobuf_archive -iquote bazel-out/k8-opt/bin/external/protobuf_archive -iquote external/com_googlesource_code_re2 -iquote bazel-out/k8-opt/genfiles/external/com_googlesource_code_re2 -iquote bazel-out/k8-opt/bin/external/com_googlesource_code_re2 -iquote external/farmhash_archive -iquote bazel-out/k8-opt/genfiles/external/farmhash_archive -iquote bazel-out/k8-opt/bin/external/farmhash_archive -iquote external/fft2d -iquote bazel-out/k8-opt/genfiles/external/fft2d -iquote bazel-out/k8-opt/bin/external/fft2d -iquote external/highwayhash -iquote bazel-out/k8-opt/genfiles/external/highwayhash -iquote bazel-out/k8-opt/bin/external/highwayhash -iquote external/zlib_archive -iquote bazel-out/k8-opt/genfiles/external/zlib_archive -iquote bazel-out/k8-opt/bin/external/zlib_archive -iquote external/llvm -iquote bazel-out/k8-opt/genfiles/external/llvm -iquote bazel-out/k8-opt/bin/external/llvm -isystem external/eigen_archive -isystem bazel-out/k8-opt/genfiles/external/eigen_archive -isystem bazel-out/k8-opt/bin/external/eigen_archive -isystem external/gif_archive/lib -isystem bazel-out/k8-opt/genfiles/external/gif_archive/lib -isystem bazel-out/k8-opt/bin/external/gif_archive/lib -isystem external/protobuf_archive/src -isystem bazel-out/k8-opt/genfiles/external/protobuf_archive/src -isystem bazel-out/k8-opt/bin/external/protobuf_archive/src -isystem external/farmhash_archive/src -isystem bazel-out/k8-opt/genfiles/external/farmhash_archive/src -isystem bazel-out/k8-opt/bin/external/farmhash_archive/src '-march=nocona' '-mtune=haswell' -ftree-vectorize -fPIC -fstack-protector-strong -O2 '-march=nocona' '-mtune=haswell' -fvisibility-inlines-hidden '-fmessage-length=0' -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c tensorflow/compiler/xla/service/cpu/disassembler.cc -o bazel-out/k8-opt/bin/tensorflow/compiler/xla/service/cpu/_objs/disassembler/disassembler.pic.o)
Execution platform: @bazel_tools//platforms:host_platform
tensorflow/compiler/xla/service/cpu/disassembler.cc: In member function 'xla::StatusOr<xla::cpu::DisassemblerResult> xla::cpu::Disassembler::DisassembleObjectFile(const llvm::object::ObjectFile&) const':
tensorflow/compiler/xla/service/cpu/disassembler.cc:93:29: error: no matching function for call to 'llvm::object::SectionRef::getContents() const'
         section.getContents();
                             ^
In file included from ./tensorflow/compiler/xla/service/cpu/disassembler.h:28:0,
                 from tensorflow/compiler/xla/service/cpu/disassembler.cc:16:
/home/conda/feedstock_root/build_artifacts/tensorflow_1594315493966/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include/llvm/Object/ObjectFile.h:430:24: note: candidate: std::error_code llvm::object::SectionRef::getContents(llvm::StringRef&) const
 inline std::error_code SectionRef::getContents(StringRef &Result) const {
                        ^
```

**Comment by brendanf** [comment]
Looks like the version of `llvmdev` is probably wrong.

**Comment by brendanf** [comment]
```
/home/conda/feedstock_root/build_artifacts/tensorflow_1594330949484/_build_env/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/5.4.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld.gold: error: cannot find -lLLVMAArch64AsmPrinter
/home/conda/feedstock_root/build_artifacts/tensorflow_1594330949484/_build_env/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/5.4.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld.gold: error: cannot find -lLLVMARMAsmPrinter
/home/conda/feedstock_root/build_artifacts/tensorflow_1594330949484/_build_env/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/5.4.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld.gold: error: cannot find -lLLVMX86AsmPrinter
```

**Comment by brendanf** [comment]
@conda-forge/tensorflow This should be ready to go now.

**Comment by marcelotrevisani** [comment]
LGTM, I am going to merge this, any problem we can fix it later

**Pull request merged**
