### PR TITLE
Migrate libprotobuf, grpcio, icu

### PR DESCRIPTION
**Pull request by hmaarrfk**
Supersedes https://github.com/conda-forge/tensorflow-feedstock/pull/140
Should be merged after: https://github.com/conda-forge/tensorflow-feedstock/pull/142

Closes https://github.com/conda-forge/tensorflow-feedstock/pull/152#issuecomment-950340848
Closes #163 
Closes #165 
Closes #168

Needs:
- [x] ~~https://github.com/conda-forge/tensorboard-data-server-feedstock/pull/6 ~~ <-- needed for openssl migration, but rust can't use openssl3????, we can do this later...

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by 183amir** [comment]
the builds are done and ready in https://anaconda.org/amir183/repo osx-arm64 builds failed though https://gitlab.idiap.ch/bob/conda/pipelines/55809

**Comment by hmaarrfk** [comment]
thanks. i think we will have to wait for cuda though

**Comment by h-vetinari** [comment]
Alright, time to revv those engines here again. ToDos:
- [ ] rebase
- [ ] New tensorflow point releases for a bunch of CVES
- [ ] ICU migration? @xhochy, please let us know if you'd like this to be covered in this PR as well!
- [ ] Centralize bazel scripts (see [here](https://github.com/conda-forge/tensorflow-feedstock/pull/157#discussion_r738226024)) - not a blocker, but would be great to have ASAP

**Comment by xhochy** [comment]
>  ICU migration? @xhochy, please let us know if you'd like this to be covered in this PR as well!

Yes, would be preferred.

**Comment by wolfv** [comment]
Just fyi I saw on twitter that 2.6.2 is imminent as well.

**Comment by wolfv** [comment]
https://github.com/tensorflow/tensorflow/pull/52930

**Comment by xhochy** [comment]
We should rebase this and see whether get it green before the release or not. We can still opt to do 2.6.2 at the same time but I guess a new version also means new (additional) trouble.

**Comment by wolfv** [comment]
looks great! Should I kick off a build?

**Comment by xhochy** [comment]
This should probably also increase the build number?

**Comment by wolfv** [comment]
Well, at least the hash should definitely change anyways :)

**Comment by h-vetinari** [comment]
Can we take care of #162 as well?

**Comment by atrawog** [comment]
I just tested it and a build-locally is working fine for linux_64_cuda_compiler_version11.2cudnn8python3.9.____cpython.

**Comment by h-vetinari** [comment]
@hmaarrfk where do we stand here? Prefer to skip dealing with #162 for now?
@wolfv offered to kick of some builds, but we should have some agreement on the code changes before we do that.

**Comment by wolfv** [comment]
Hey, yeah, more than happy to kick off some builds.
To fix #162 it would be enough to add the `cudatoolkit` dependency on tensorflow as well. But as you want!

Once you give the thumbsup we can start the builds :)

**Comment by hmaarrfk** [comment]
I think we should solve #162 as part of this. The builds take time. Lets agree on a solution there?

**Comment by 183amir** [comment]
https://gitlab.idiap.ch/bob/conda/pipelines/56044

**Comment by hmaarrfk** [comment]
There was one successful CPU build for linux. Seems like the recipe is good enough?

**Review by h-vetinari — APPROVED** [review]
LGTM, thanks @hmaarrfk! :)

**Comment by wolfv** [comment]
If you want a build on OVH, just let me or @atrawog know :)

**Comment by hmaarrfk** [comment]
what is OVH? i don't ont be able to build Linux until the weekend.

**Comment by maresb** [comment]
OVH is a French cloud provider. I think that @wolfv is offering to run the builds there.

**Comment by 183amir** [comment]
All the builds should finish soon on the link I posted above. Even the red ones have finished uploading packages.

**Comment by h-vetinari** [comment]
Just noticed that we're not building `tensorflow-cpu` for osx (despite there not being any skip for that output).

I believe we have to change something along the lines of
```diff
-   {% set tensorflow_cpu_gpu = "tensorflow-cpu" %}   # [cuda_compiler_version == "None"]
+   {% set tensorflow_cpu_gpu = "tensorflow-cpu" %}   # [cuda_compiler_version == "None" or cuda_compiler_version is undefined]
    {% set tensorflow_cpu_gpu = "tensorflow-gpu" %}   # [cuda_compiler_version != "None"]
    - name: {{ tensorflow_cpu_gpu }}

**Comment by h-vetinari** [comment]
Also note that there have been no osx-builds since the build-string adaptations. I cannot select `tensorflow =*=cpu*` for osx, & together with the absence of `tf-cpu`, I'm now blocked for osx in https://github.com/conda-forge/staged-recipes/pull/16888

**Comment by hmaarrfk** [comment]
feel free to push to my branch. I'm away from my keyboard for a while.

**Comment by hmaarrfk** [comment]
or suggest

**Comment by h-vetinari** [comment]
I think this has now converged? Any other thoughts @conda-forge/tensorflow?

Then I'd say we can do one final round of builds? My guess would be that it's easiest if @wolfv (as a cf/core member) does it again, but I'm also very happy to see that @atrawog & @183amir are willing to help out with builds - I'll leave the details & preferences of whose builds to take to the cf/core members doing the final upload.

**Comment by h-vetinari** [comment]
BTW, I verified that https://github.com/conda-forge/tensorflow-feedstock/pull/144/commits/13131bcd998cc071db4047dfd698b3677acb2d44 works (for both x64 & arm):
```
BUILD START: ['tensorflow-base-2.6.0-cpu_py37h6ec3172_3.tar.bz2', 'tensorflow-estimator-2.6.0-cpu_py37h20a3113_3.tar.bz2', 'tensorflow-2.6.0-cpu_py37h20a3113_3.tar.bz2', 'tensorflow-cpu-2.6.0-cpu_py37he781eb1_3.tar.bz2']
```

**Comment by h-vetinari** [comment]
Was looking over the [list](https://github.com/conda-forge/tensorflow-feedstock/pull/144#issuecomment-960571966) above again, and realised we hadn't taken care of the version bump for the CVEs.

Here's an updated list:
- [x] rebase
- [x] New tensorflow point releases for a bunch of CVES
- [x] ICU migration
- [ ] Centralize bazel scripts (see [here](https://github.com/conda-forge/tensorflow-feedstock/pull/157#discussion_r738226024)) - not a blocker, but would be great to have ASAP

**Comment by wolfv** [comment]
Working on the bazel toolchain port now
@atrawog is working at QuantStack as well, so if he or I do it it's "the same" :)

If you give us a sign, we can kick off the builds. We will upload them first to an S3 bucket, paste the outputs here, and then manually upload them first to my channel and then copy them to conda-forge.

**Comment by h-vetinari** [comment]
> If you give us a sign, we can kick off the builds.

Well, I'd love to say "Ignite the engines!", but I just saw that we have some ICE now (not sure if flaky):
```
[2,917 / 4,696] Compiling tensorflow/compiler/mlir/tensorflow/ir/tf_ops.cc; 1008s local ... (2 actions running)
ERROR: /home/conda/feedstock_root/build_artifacts/tensorflow-split_1636608986500/work/tensorflow/compiler/mlir/tensorflow/BUILD:569:11: Compiling tensorflow/compiler/mlir/tensorflow/ir/tf_ops.cc failed: (Exit 4): x86_64-conda-linux-gnu-gcc failed: error executing command 
  (cd /home/conda/feedstock_root/build_artifacts/tensorflow-split_1636608986500/_build_env/share/bazel/24274b892a5a96b0969ae0a8b8d7a53e/execroot/org_tensorflow && \
  exec env - \
    PATH=/home/conda/feedstock_root/build_artifacts/tensorflow-split_1636608986500/work:/home/conda/feedstock_root/build_artifacts/tensorflow-split_1636608986500/_build_env/bin:/home/conda/feedstock_root/build_artifacts/tensorflow-split_1636608986500/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin:/opt/conda/condabin:/home/conda/feedstock_root/build_artifacts/tensorflow-split_1636608986500/_build_env:/home/conda/feedstock_root/build_artifacts/tensorflow-split_1636608986500/_build_env/bin:/home/conda/feedstock_root/build_artifacts/tensorflow-split_1636608986500/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac:/home/conda/feedstock_root/build_artifacts/tensorflow-split_1636608986500/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin:/opt/conda/bin:/opt/conda/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/conda/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/home/conda/feedstock_root/build_artifacts/tensorflow-split_1636608986500/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python \
    PYTHON_LIB_PATH=/home/conda/feedstock_root/build_artifacts/tensorflow-split_1636608986500/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.8/site-packages \
    TF2_BEHAVIOR=1 \
    TF_SYSTEM_LIBS=absl_py,astor_archive,astunparse_archive,boringssl,com_github_googlecloudplatform_google_cloud_cpp,com_github_grpc_grpc,com_google_protobuf,curl,cython,dill_archive,flatbuffers,gast_archive,gif,icu,libjpeg_turbo,org_sqlite,png,pybind11,snappy,zlib \
  /home/conda/feedstock_root/build_artifacts/tensorflow-split_1636608986500/_build_env/bin/x86_64-conda-linux-gnu-gcc -MD -MF bazel-out/k8-opt/bin/tensorflow/compiler/mlir/tensorflow/_objs/tensorflow_ops/tf_ops.pic.d '-frandom-seed=bazel-out/k8-opt/bin/tensorflow/compiler/mlir/tensorflow/_objs/tensorflow_ops/tf_ops.pic.o' -fPIC -DLLVM_ENABLE_STATS -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DLLVM_BUILD_GLOBAL_ISEL -DEIGEN_MPL2_ONLY '-DEIGEN_MAX_ALIGN_BYTES=64' -iquote . -iquote bazel-out/k8-opt/bin -iquote external/llvm-project -iquote bazel-out/k8-opt/bin/external/llvm-project -iquote external/zlib -iquote bazel-out/k8-opt/bin/external/zlib -iquote external/com_google_absl -iquote bazel-out/k8-opt/bin/external/com_google_absl -iquote external/nsync -iquote bazel-out/k8-opt/bin/external/nsync -iquote external/eigen_archive -iquote bazel-out/k8-opt/bin/external/eigen_archive -iquote external/gif -iquote bazel-out/k8-opt/bin/external/gif -iquote external/libjpeg_turbo -iquote bazel-out/k8-opt/bin/external/libjpeg_turbo -iquote external/com_google_protobuf -iquote bazel-out/k8-opt/bin/external/com_google_protobuf -iquote external/com_googlesource_code_re2 -iquote bazel-out/k8-opt/bin/external/com_googlesource_code_re2 -iquote external/farmhash_archive -iquote bazel-out/k8-opt/bin/external/farmhash_archive -iquote external/fft2d -iquote bazel-out/k8-opt/bin/external/fft2d -iquote external/highwayhash -iquote bazel-out/k8-opt/bin/external/highwayhash -iquote external/double_conversion -iquote bazel-out/k8-opt/bin/external/double_conversion -Ibazel-out/k8-opt/bin/external/llvm-project/mlir/_virtual_includes/BuiltinAttributesIncGen -Ibazel-out/k8-opt/bin/external/llvm-project/mlir/_virtual_includes/BuiltinDialectIncGen -Ibazel-out/k8-opt/bin/external/llvm-project/mlir/_virtual_includes/BuiltinLocationAttributesIncGen -Ibazel-out/k8-opt/bin/external/llvm-project/mlir/_virtual_includes/BuiltinOpsIncGen -Ibazel-out/k8-opt/bin/external/llvm-project/mlir/_virtual_includes/BuiltinTypeInterfacesIncGen -Ibazel-out/k8-opt/bin/external/llvm-project/mlir/_virtual_includes/BuiltinTypesIncGen -Ibazel-out/k8-opt/bin/external/llvm-project/mlir/_virtual_includes/CallOpInterfacesIncGen -Ibazel-out/k8-opt/bin/external/llvm-project/mlir/_virtual_includes/CastOpInterfacesIncGen -Ibazel-out/k8-opt/bin/external/llvm-project/mlir/_virtual_includes/InferTypeOpInterfaceIncGen -Ibazel-out/k8-opt/bin/external/llvm-project/mlir/_virtual_includes/OpAsmInterfaceIncGen -Ibazel-out/k8-opt/bin/external/llvm-project/mlir/_virtual_includes/RegionKindInterfaceIncGen -Ibazel-out/k8-opt/bin/external/llvm-project/mlir/_virtual_includes/SideEffectInterfacesIncGen -Ibazel-out/k8-opt/bin/external/llvm-project/mlir/_virtual_includes/SubElementInterfacesIncGen -Ibazel-out/k8-opt/bin/external/llvm-project/mlir/_virtual_includes/SymbolInterfacesIncGen -Ibazel-out/k8-opt/bin/external/llvm-project/mlir/_virtual_includes/TensorEncodingIncGen -Ibazel-out/k8-opt/bin/external/llvm-project/mlir/_virtual_includes/ParserTokenKinds -Ibazel-out/k8-opt/bin/external/llvm-project/mlir/_virtual_includes/ControlFlowInterfacesIncGen -Ibazel-out/k8-opt/bin/external/llvm-project/mlir/_virtual_includes/DerivedAttributeOpInterfaceIncGen -Ibazel-out/k8-opt/bin/external/llvm-project/mlir/_virtual_includes/LoopLikeInterfaceIncGen -Ibazel-out/k8-opt/bin/external/llvm-project/mlir/_virtual_includes/StandardOpsIncGen -Ibazel-out/k8-opt/bin/external/llvm-project/mlir/_virtual_includes/VectorInterfacesIncGen -isystem external/llvm-project/llvm/include -isystem bazel-out/k8-opt/bin/external/llvm-project/llvm/include -isystem external/llvm-project/mlir/include -isystem bazel-out/k8-opt/bin/external/llvm-project/mlir/include -isystem external/nsync/public -isystem bazel-out/k8-opt/bin/external/nsync/public -isystem third_party/eigen3/mkl_include -isystem bazel-out/k8-opt/bin/third_party/eigen3/mkl_include -isystem external/eigen_archive -isystem bazel-out/k8-opt/bin/external/eigen_archive -isystem external/farmhash_archive/src -isystem bazel-out/k8-opt/bin/external/farmhash_archive/src -isystem external/double_conversion -isystem bazel-out/k8-opt/bin/external/double_conversion -isystem /home/conda/feedstock_root/build_artifacts/tensorflow-split_1636608986500/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/include '-march=nocona' '-mtune=haswell' -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/conda/feedstock_root/build_artifacts/tensorflow-split_1636608986500/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/include '-fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/tensorflow-split_1636608986500/work=/usr/local/src/conda/tensorflow-split-2.6.2' '-fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/tensorflow-split_1636608986500/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac=/usr/local/src/conda-prefix' -DNDEBUG '-D_FORTIFY_SOURCE=2' -O2 -isystem /home/conda/feedstock_root/build_artifacts/tensorflow-split_1636608986500/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/include -fvisibility-inlines-hidden '-std=c++17' '-fmessage-length=0' '-march=nocona' '-mtune=haswell' -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/conda/feedstock_root/build_artifacts/tensorflow-split_1636608986500/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/include '-fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/tensorflow-split_1636608986500/work=/usr/local/src/conda/tensorflow-split-2.6.2' '-fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/tensorflow-split_1636608986500/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac=/usr/local/src/conda-prefix' -DNDEBUG '-D_FORTIFY_SOURCE=2' -O2 -isystem /home/conda/feedstock_root/build_artifacts/tensorflow-split_1636608986500/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/include -w -DAUTOLOAD_DYNAMIC_KERNELS '-march=nocona' '-mtune=haswell' -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/conda/feedstock_root/build_artifacts/tensorflow-split_1636608986500/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/include '-fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/tensorflow-split_1636608986500/work=/usr/local/src/conda/tensorflow-split-2.6.2' '-fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/tensorflow-split_1636608986500/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac=/usr/local/src/conda-prefix' '-std=c++14' -c tensorflow/compiler/mlir/tensorflow/ir/tf_ops.cc -o bazel-out/k8-opt/bin/tensorflow/compiler/mlir/tensorflow/_objs/tensorflow_ops/tf_ops.pic.o)
Execution platform: @local_execution_config_platform//:platform
{standard input}: Assembler messages:
{standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
x86_64-conda-linux-gnu-gcc: internal compiler error: Killed (program cc1plus)
```

**Comment by wolfv** [comment]
Yes, that's just Azure running out of memory! Happened before :)

**Comment by h-vetinari** [comment]
> 
> 
> Yes, that's just Azure running out of memory! Happened before :)

Alrighty! I think we've had long enough for people to chime in here over the last two weeks, I say "fire away!" 🙃

**Comment by wolfv** [comment]
Here is the PR for bazel-toolchain: https://github.com/conda-forge/bazel-toolchain-feedstock/pull/5

**Comment by h-vetinari** [comment]
> 
> 
> Here is the PR for bazel-toolchain: [conda-forge/bazel-toolchain-feedstock#5](https://github.com/conda-forge/bazel-toolchain-feedstock/pull/5)

Seeing that this PR matured very quickly, do you want to try this with this PR already, or can we postpone that to 2.7.0?

**Comment by h-vetinari** [comment]
> or can we postpone that to 2.7.0?

That would be my preference, BTW. It would be good to finally get this out the door. :)

**Comment by h-vetinari** [comment]
New grpc migrator is [here](https://github.com/conda-forge/tensorflow-feedstock/pull/171), but again, I propose to handle this as part of 2.7.0

@wolfv @atrawog 
Any updates on the current status?

**Comment by h-vetinari** [comment]
> Any updates on the current status?

If there are no builds running yet, I'd like to add a run-export to `libtensorflow_cc`, see [here](https://github.com/conda-forge/staged-recipes/pull/16888/files#r750637986) why.

**Comment by atrawog** [comment]
The building is working for all variants except `linux_64_cuda_compiler_version10.2cudnn7python3.7.____cpython` (which might be a fluke during building and I will run the build again).

All other variants build the package fine, but fail during testing because mama fails to resolve the depenencies for keras.
```
EST END: /home/conda/feedstock_root/build_artifacts/linux-64/tensorflow-estimator-2.6.2-cuda102py37h80be449_0.tar.bz2
TEST START: /home/conda/feedstock_root/build_artifacts/linux-64/tensorflow-2.6.2-cuda102py37h80be449_0.tar.bz2
Multiple meta files found. The meta.yaml file in the base directory (/tmp/tmp229xc4nb/info/recipe) will be used.
WARNING:conda_build.utils:Multiple meta files found. The meta.yaml file in the base directory (/tmp/tmp229xc4nb/info/recipe) will be used.
WARNING conda_build.utils:find_recipe(1320): Multiple meta files found. The meta.yaml file in the base directory (/tmp/tmp229xc4nb/info/recipe) will be used.
[34mReloading output folder: [0m[34m/home/conda/feedstock_root/[0m[34mbuild_artifacts[0m
[2K
build_artifacts/linux-64 [] (--:--) Finalizing...
[1A[2K
build_artifacts/linux-64 [] (--:--) Done
[1A[0K[2K
build_artifacts/linux-64 [] (00m:00s) Done
[2K
build_artifacts/noarch   [] (--:--) Finalizing...
[1A[2K
build_artifacts/noarch   [] (--:--) Done
[1A[0K[2K
build_artifacts/noarch   [] (00m:00s) Done
Mamba failed to solve:
 - tensorflow 2.6.2.* cuda102py37h80be449_0
 - cudatoolkit 10.2|10.2.*
 - libgcc-ng >=7.5.0
 - libstdcxx-ng >=7.5.0
 - openssl >=1.1.1l,<1.1.2a
 - python >=3.7,<3.8.0a0
 - python_abi 3.7.* *_cp37m
 - tensorflow-base 2.6.2.* cuda102py37hd5ceeda_0
 - tensorflow-estimator 2.6.2.* cuda102py37h80be449_0
 - pip
 - python

with channels:

The reported errors are:
- Encountered problems while solving:
-   - package tensorflow-base-2.6.2-cuda102py37hd5ceeda_0 requires keras >=2.6,<2.7, but none of the providers can be installed
- 
failed to get install actions, retrying.  exception was: 
WARNING:conda_build.build:failed to get install actions, retrying.  exception was: 
WARNING conda_build.build:test(2874): failed to get install actions, retrying.  exception was: 
Tests failed for tensorflow-2.6.2-cuda102py37h80be449_0.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
WARNING:conda_build.build:Tests failed for tensorflow-2.6.2-cuda102py37h80be449_0.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
WARNING conda_build.build:tests_failed(2970): Tests failed for tensorflow-2.6.2-cuda102py37h80be449_0.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
TESTS FAILED: tensorflow-2.6.2-cuda102py37h80be449_0.tar.bz2
valid configs are {'linux_64_cuda_compiler_versionNonecudnnundefinedpython3.7.____cpython', 'linux_64_cuda_compiler_version11.1cudnn8python3.8.____cpython', 'linux_64_cuda_compiler_version11.0cudnn8python3.7.____cpython', 'osx_64_python3.8.____cpython', 'linux_64_cuda_compiler_versionNonecudnnundefinedpython3.8.____cpython', 'linux_64_cuda_compiler_versionNonecudnnundefinedpython3.9.____cpython', 'osx_64_python3.7.____cpython', 'linux_64_cuda_compiler_version11.1cudnn8python3.7.____cpython', 'linux_64_cuda_compiler_version10.2cudnn7python3.9.____cpython', 'linux_64_cuda_compiler_version10.2cudnn7python3.7.____cpython', 'linux_64_cuda_compiler_version11.2cudnn8python3.9.____cpython', 'osx_64_python3.9.____cpython', 'linux_64_cuda_compiler_version11.2cudnn8python3.8.____cpython', 'linux_64_cuda_compiler_version11.1cudnn8python3.9.____cpython', 'linux_64_cuda_compiler_version11.0cudnn8python3.8.____cpython', 'linux_64_cuda_compiler_version10.2cudnn7python3.8.____cpython', 'linux_64_cuda_compiler_version11.2cudnn8python3.7.____cpython', 'linux_64_cuda_compiler_version11.0cudnn8python3.9.____cpython', 'osx_arm64_python3.9.____cpython', 'osx_arm64_python3.8.____cpython'}
Using linux_64_cuda_compiler_version10.2cudnn7python3.7.____cpython configuration
Traceback (most recent call last):
  File "/home/ubuntu/feedstock/./build-locally.py", line 101, in <module>
    main()
  File "/home/ubuntu/feedstock/./build-locally.py", line 95, in main
    run_docker_build(ns)
  File "/home/ubuntu/feedstock/./build-locally.py", line 33, in run_docker_build
    subprocess.check_call([script])
  File "/home/ubuntu/micromamba/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['.scripts/run_docker_build.sh']' returned non-zero exit status 1.
```

**Comment by h-vetinari** [comment]
That's really weird. I did tighten the restriction in https://github.com/conda-forge/tensorflow-feedstock/pull/144/commits/df8a7ba2a5d85c43bee9b22ab8ffc40ad63dcc7f from `- keras >=2.6,<3` to ` - keras >=2.6,<2.7`, but that shouldn't matter because so far there's only a 2.6 [build](https://anaconda.org/conda-forge/keras/files) for keras anyway...

**Comment by izahn** [comment]
I think the problem is https://github.com/conda-forge/keras-feedstock/blob/1e627c9e3a4b67d661d6b4316dd145008fbf19e6/recipe/meta.yaml#L25

**Comment by hmaarrfk** [comment]
So we only need to pin to the major/minor not patch.

**Comment by h-vetinari** [comment]
> So we only need to pin to the major/minor not patch.

Yeah, I'd say that's reasonable. Even though there's no hard guarantee that patch-releases are ABI-compatible, it gets a bit murky if there are no patch-releases for all components. I'd say major/minor should be (more than) good enough.

**Comment by wolfv** [comment]
keras isn't compiled, though, so API is the only thing that should matter, right? I would think that tensorflow guarantees enough stability in that sense, doesn't it?

**Comment by h-vetinari** [comment]
Yeah, you're right. I was already thinking in terms of the run-exports that we'll [need](https://github.com/conda-forge/staged-recipes/pull/16888/files#r750637986) to add to `libtensorflow{,_cc}`. Do you want to pin to patch level there, or also major_minor?

**Comment by wolfv** [comment]
To be honest, I have no idea. I also don't know where these libraries are used. I'm not sure tensorflow "cares" about ABI stability there since the main product is the python library, but I have no deep knowledge of this. I checked ABI Laboratory quickly but unfortunately tensorflow isn't tracked: https://abi-laboratory.pro/index.php?view=tracker

**Comment by h-vetinari** [comment]
> I also don't know where these libraries are used.

Well, it'll be used more and more once we have decent packages, but there's at least one staged-recipe already that needs it: https://github.com/conda-forge/staged-recipes/pull/16888

>  I'm not sure tensorflow "cares" about ABI stability there since the main product is the python library

I went with the conservative choice for now and pinned down to patch-level

**Comment by wolfv** [comment]
I did a bit of googling: https://github.com/tensorflow/custom-op and https://pgaleone.eu/tensorflow/bazel/abi/c++/2021/04/01/tensorflow-custom-ops-bazel-abi-compatibility/ mention ABI compatibility.

Not sure what the conclusion is regarding compatible version though :D

**Comment by hmaarrfk** [comment]
In the early days, Keras was always playing catchup to changes in tensorflow.

To my knowledge, after Google acquired keras, tensorflow and keras started getting released in step.

Therefore, keras 2.6.0 is only supported with tensorflow 2.6.0.

Honestly, I guess the maintainers thought that if tensorflow 2.6.2 would be released, so would keras 2.6.2. But maybe tf has grown up to the point where they want stability.

**Comment by hmaarrfk** [comment]
I made the PR, if you are impatient, you can merge it.

https://github.com/conda-forge/keras-feedstock/pull/55

**Comment by h-vetinari** [comment]
OK, thanks for creating & merging the keras-PR @hmaarrfk!

Now everything should be ready to go again? 🤞

**Comment by xhochy** [comment]
We were missing the `lief_dev` lines. I've added them again and will run OSX builds. Tried to run things over night but everything took forever :D

**Comment by xhochy** [comment]
The OSX builds are located at https://anaconda.org/uwe.korn with the following logs:

- [osx_64_python3.7.____cpython.log](https://gist.github.com/xhochy/16e391c8b7b7347f6e0179b09430e54f)
- [osx_64_python3.8.____cpython.log](https://gist.github.com/xhochy/ac25fba558f4e3eff3bd5fcac67eac90)
- [osx_64_python3.9.____cpython.log](https://gist.github.com/xhochy/cd82ea68420e85799fd71564ccff6e81)
- [osx_arm64_python3.8.____cpython.log](https://gist.github.com/xhochy/44c8b71173bf011e8ddc7ba209cdcd18)
- [osx_arm64_python3.9.____cpython.log](https://gist.github.com/xhochy/40cfa420bf03b5e2e265358b7bf9a397)

The Linux builds are located at https://anaconda.org/uwe.korn-tf-gpu with the following logs:

-  [linux_64_cuda_compiler_versionNonecudnnundefinedpython3.9.____cpython.log](https://gist.github.com/xhochy/668e3040aa9f415ab0206ee8343d6ceb)
-  [linux_64_cuda_compiler_versionNonecudnnundefinedpython3.8.____cpython.log](https://gist.github.com/xhochy/16c5f0b3d241c4cfcae80829091dc057)
-  [linux_64_cuda_compiler_versionNonecudnnundefinedpython3.7.____cpython.log](https://gist.github.com/xhochy/78c3a3b79a7b7107bfa2d506dc75fdb1)
-  [linux_64_cuda_compiler_version11.2cudnn8python3.9.____cpython.log](https://gist.github.com/xhochy/90468079a92246b66075a1cd7c120902)
-  [linux_64_cuda_compiler_version11.2cudnn8python3.8.____cpython.log](https://gist.github.com/xhochy/33f9bd5eae8f57421b07b1b8133b218c)
-  [linux_64_cuda_compiler_version11.2cudnn8python3.7.____cpython.log](https://gist.github.com/xhochy/c0cd15f99075cfd7959b902be3f8de79)
-  [linux_64_cuda_compiler_version11.1cudnn8python3.9.____cpython.log](https://gist.github.com/xhochy/c3febf8fbc42a079d0262d34e6331593)
-  [linux_64_cuda_compiler_version11.1cudnn8python3.8.____cpython.log](https://gist.github.com/xhochy/0178bf3aa0575ebcbfb18032360e1a3a)
-  [linux_64_cuda_compiler_version11.1cudnn8python3.7.____cpython.log](https://gist.github.com/xhochy/dd1acb93c374b04d68da341701d793ea)
-  [linux_64_cuda_compiler_version11.1cudnn8python3.8.____cpython.log](https://gist.github.com/xhochy/fb3149e2418f6302c3029d6728ccc5f9)
-  [linux_64_cuda_compiler_version11.1cudnn8python3.7.____cpython.log](https://gist.github.com/xhochy/ecd0448727e5b7cb0d72d7997413d94c)
-  [linux_64_cuda_compiler_version11.0cudnn8python3.9.____cpython.log](https://gist.github.com/xhochy/685119cf09b3802664acee888fe2c998)
-  [linux_64_cuda_compiler_version11.0cudnn8python3.8.____cpython.log](https://gist.github.com/xhochy/052d7923270be47b2b32482101510ea8)
-  [linux_64_cuda_compiler_version11.0cudnn8python3.7.____cpython.log](https://gist.github.com/xhochy/c9dbb75b8665256e657369adbf727566)
-  [linux_64_cuda_compiler_version10.2cudnn7python3.9.____cpython.log](https://gist.github.com/xhochy/d7e5edba720b8f6ebe943ced77cfd960)
-  [linux_64_cuda_compiler_version10.2cudnn7python3.8.____cpython.log](https://gist.github.com/xhochy/1fdd68751a52835b21c655f51ee5c9d4)
-  [linux_64_cuda_compiler_version10.2cudnn7python3.7.____cpython.log](https://gist.github.com/xhochy/8c172afcaf7475a3b2babe5030080a58)

@wolfv as conda-forge/core, can you please approve or 👍 ? Then I would merge and copy over to conda-forge.

**Comment by wolfv** [comment]
Looks good, go ahead! :+1:

**Comment by xhochy** [comment]
Packages were copied, let's get on with the next migrations.

**Pull request merged**
