### PR TITLE
RFC: libtfkernel_mlir_ops

### PR DESCRIPTION
**Pull request by xhochy**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xhochy** [comment]
This worked 🙌

**Comment by xhochy** [comment]
Sadly loading this doesn't work in a split build as some math operations are loaded twice (which is not allowed). Possibly the best approach is to do the same as we did with LLVM: Build some intermediate static libraries and reuse them in a later build.

**Comment by ngam** [comment]
> Sadly loading this doesn't work in a split build as some math operations are loaded twice (which is not allowed). Possibly the best approach is to do the same as we did with LLVM: Build some intermediate static libraries and reuse them in a later build.

Sorry to hear this.

I am curious if you think we can trim some of the compilations. I do notice that we end up compiling for ROCm and TPUs even though we don't really support those. Or maybe I am misreading the compilation logs?

**Comment by h-vetinari** [comment]
> Possibly the best approach is to do the same as we did with LLVM: Build some intermediate static libraries and reuse them in a later build.

This sounds fine to me TBH. Whether the intermediate libs are static or dynamic doesn't really matter IMO.

**Pull request closed without merging**
