### PR TITLE
Icu70 and 2.7.1

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
To my knowledge, this now succesfully builds on Cuda 11.2

I'm willing to start building this out if somebody else wants to build OSX.

In terms of OSX feasibility, i've mostly pulled all the patches I can think of from xhochy's branch so I think it should work.

**Comment by xhochy** [comment]
I can build this!

**Comment by hmaarrfk** [comment]
Thanks. I'm going to start building these locally.

I'll let you build OSX?

**Comment by xhochy** [comment]
Built all except one on `osx-*`, all looking good. I'll upload them soon.

**Comment by xhochy** [comment]
Uploaded the builds at https://anaconda.org/uwe.korn/repo with the logs:

- https://gist.github.com/xhochy/f0a26cec2ecad467499a6f6eebc62020
- https://gist.github.com/xhochy/eb9e8a846741f5b9d647afa3f4669b61
- https://gist.github.com/xhochy/a00afb34429e086f515dc7179055d960
- https://gist.github.com/xhochy/14c8f4beb979e88451bfd45d9b70f64e
- https://gist.github.com/xhochy/dcc3d9f42c91f1d286e5faae95248958
- https://gist.github.com/xhochy/5520b6c86f706a6f8859cf6d1b084ad3
- https://gist.github.com/xhochy/4e99cb715a00449a6b66660e2c8f37fb

**Comment by hmaarrfk** [comment]
linux builds are maybe 1/2 way through. Takes a while....

**Comment by hmaarrfk** [comment]
13 / 20 builds.

**Comment by hmaarrfk** [comment]
Linux Builds: https://anaconda.org/mark.harfouche/ 
* label: `cfep03`
* 4x4 GPU Builds
* 4 CPU builds


Logfiles: [log_files.zip](https://github.com/conda-forge/tensorflow-feedstock/files/8657214/log_files.zip)

@xhochy do you want to upload them?

**Review by xhochy — APPROVED** [review]
Will check the logs and upload later (1-4h)

**Pull request merged**
