### PR TITLE
Rebuild icu72 and 2.11.1

### PR DESCRIPTION
**Pull request by hmaarrfk**
- [ ] linux + cuda
- [ ] linux + cpu 
- [x] OSX + x86 anaconda.com/mark.harfouche `cfep03` label
- [x] OSX + arm [osx_logs.zip](https://github.com/conda-forge/tensorflow-feedstock/files/11071693/osx_logs.zip)

Closes #312 

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
lets just see how far it gets then we can trigger builds locally.

**Comment by hmaarrfk** [comment]
builds are chugging along. all builds should be done by tomorrow.

**Comment by hmaarrfk** [comment]
hmm.... i build the old branch on linux accidentally. rebuliding now. should be done in 24 hours...

**Comment by hmaarrfk** [comment]
Logs for #311 

Editing the top comment is being buggy. all builds completed. copying over now.

- [x] linux + cuda anaconda.com/mark.harfouche `cfep03` label
- [x] linux + cpu [log_files.zip](https://github.com/conda-forge/tensorflow-feedstock/files/11078620/log_files.zip)
- [x] OSX + x86 anaconda.com/mark.harfouche `cfep03` label
- [x] OSX + arm [osx_logs.zip](https://github.com/conda-forge/tensorflow-feedstock/files/11071693/osx_logs.zip)


```
for package in tensorflow-base tensorflow tensorflow-estimator libtensorflow libtensorflow_cc tensorflow-cpu tensorflow-gpu; do
  anaconda copy --from-label cfep03 --to-label main --to-owner conda-forge mark.harfouche/${package}/2.11.1
done
```

**Comment by jan-janssen** [comment]
It seems like the tests failed and the builds were never uploaded. @hmaarrfk can you take a look at this?

**Pull request merged**
