### PR TITLE
update to 1.8.0

### PR DESCRIPTION
**Pull request by dougalsutherland**
Based on @gilbertfrancois's changes in #53, but avoiding merge conflicts with #52.

### CODE REVIEW

**Comment by dougalsutherland** [comment]
@gilbertfrancois: Can you clarify what you meant by https://github.com/conda-forge/tensorflow-feedstock/pull/53#issuecomment-387744099? I haven't tested locally, but does this work now that the updated `tensorboard` package is available?

**Comment by gilbertfrancois** [comment]
The packages and dependencies of #53 are all ok. However, when starting `$ tensorboard --logdir [dir]` it throws an error. The version `1.6.0` is broken too, see below:

```
(test) ubuntu@ip-172-31-8-108:~$ conda list tensor*
# packages in environment at /home/ubuntu/anaconda3/envs/test:
#
# Name                    Version                   Build  Channel
tensorboard               1.6.0                    py36_0    conda-forge
tensorflow                1.6.0                    py36_0    conda-forge

(test) ubuntu@ip-172-31-8-108:~$ tensorboard --logdir /data/logs/tfscratch/ 
Traceback (most recent call last): 
  File "/home/ubuntu/anaconda3/envs/test/bin/tensorboard", line 7, in <module> 
    from tensorflow.tensorboard.tensorboard import main 
ModuleNotFoundError: No module named 'tensorflow.tensorboard' 
```
I think I've found the solution and will update both tensorflow and tensorboard `meta.yaml` files. It is caused by the split they made in the packages but still have cross dependencies. I test before I push the new code.

**Comment by gilbertfrancois** [comment]
@dougalsutherland: The Tensorboard crash has been solved. Both the tensorflow and tensorboard `meta.yaml` files have small changes. Please add this:
```
  entry_points:
    - freeze_graph = tensorflow.python.tools.freeze_graph:run_main
    - toco_from_protos = tensorflow.contrib.lite.toco.python.toco_from_protos:main
    - toco = tensorflow.contrib.lite.toco.python.toco_wrapper:main
    - saved_model_cli = tensorflow.python.tools.saved_model_cli:main
    # We need to keep the TensorBoard command, even though the console script
    # is now declared by the tensorboard pip package. If we remove the
    # TensorBoard command, pip will inappropriately remove it during install,
    # even though the command is not removed, just moved to a different wheel.
    - tensorboard = tensorboard.main:run_main
```
to the build section in `meta.yaml`. I don't know (yet) how to add it in your pull request. I did it in #53 as well, but that build seems to have a problem with building the package for macOS py27 on Travis.

Thank you.

**Comment by sdvillal** [comment]
I agree with @gilbertfrancois regarding the entrypoints. I think we should start adding here tests for them, in particular for tensorboard.

At least for linux and mac it should be something like:

```yaml
commands:
    - tensorboard --help | grep USAGE
```

See https://github.com/conda-forge/tensorboard-feedstock/pull/8#issuecomment-387940850

I think this should work now without much hassle, and then we would close #48 and #47.

**Comment by gilbertfrancois** [comment]
Please consider reviewing and merging #53.

**Comment by sdvillal** [comment]
Commented the same there. I have no permisions to close/merge in this repo, but I think we should close this PR to avoid duplicating efforts.

**Pull request closed without merging**
